// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/access.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "io.ultimatebackend.srv.access";

export interface Access {
  id: string;
  token: string;
  tenantId: string;
  scopes: string[];
  name: string;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  createdBy: string;
}

export interface CreateAccessRequest {
  tenantId: string;
  scopes: string[];
  name: string;
  expireAt: string;
}

export interface CreateAccessResponse {
  accessToken: Access | undefined;
}

export interface DeleteAccessRequest {
  id: string;
  tenantId: string;
}

export interface DeleteAccessResponse {
  accessToken: Access | undefined;
}

export interface ReadAccessRequest {
  id: string;
  tenantId: string;
}

export interface ReadAccessResponse {
  accessToken: Access | undefined;
}

export interface FindAccessRequest {
  filter: string;
  tenantId: string;
}

export interface FindAccessResponse {
  accessToken: Access[];
}

export interface HasRightsRequest {
  token: string;
  scope: string;
  tenantId: string;
}

export interface HasRightsResponse {
  access: boolean;
}

function createBaseAccess(): Access {
  return {
    id: "",
    token: "",
    tenantId: "",
    scopes: [],
    name: "",
    createdAt: "",
    updatedAt: "",
    active: false,
    createdBy: "",
  };
}

export const Access: MessageFns<Access> = {
  encode(message: Access, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    for (const v of message.scopes) {
      writer.uint32(34).string(v!);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.createdAt !== "") {
      writer.uint32(66).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(74).string(message.updatedAt);
    }
    if (message.active !== false) {
      writer.uint32(80).bool(message.active);
    }
    if (message.createdBy !== "") {
      writer.uint32(90).string(message.createdBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Access {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Access {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      createdBy: isSet(object.createdBy) ? globalThis.String(object.createdBy) : "",
    };
  },

  toJSON(message: Access): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.createdBy !== "") {
      obj.createdBy = message.createdBy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Access>, I>>(base?: I): Access {
    return Access.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Access>, I>>(object: I): Access {
    const message = createBaseAccess();
    message.id = object.id ?? "";
    message.token = object.token ?? "";
    message.tenantId = object.tenantId ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.name = object.name ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    message.active = object.active ?? false;
    message.createdBy = object.createdBy ?? "";
    return message;
  },
};

function createBaseCreateAccessRequest(): CreateAccessRequest {
  return { tenantId: "", scopes: [], name: "", expireAt: "" };
}

export const CreateAccessRequest: MessageFns<CreateAccessRequest> = {
  encode(message: CreateAccessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenantId !== "") {
      writer.uint32(10).string(message.tenantId);
    }
    for (const v of message.scopes) {
      writer.uint32(18).string(v!);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.expireAt !== "") {
      writer.uint32(34).string(message.expireAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAccessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAccessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expireAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAccessRequest {
    return {
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      expireAt: isSet(object.expireAt) ? globalThis.String(object.expireAt) : "",
    };
  },

  toJSON(message: CreateAccessRequest): unknown {
    const obj: any = {};
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.expireAt !== "") {
      obj.expireAt = message.expireAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAccessRequest>, I>>(base?: I): CreateAccessRequest {
    return CreateAccessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAccessRequest>, I>>(object: I): CreateAccessRequest {
    const message = createBaseCreateAccessRequest();
    message.tenantId = object.tenantId ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.name = object.name ?? "";
    message.expireAt = object.expireAt ?? "";
    return message;
  },
};

function createBaseCreateAccessResponse(): CreateAccessResponse {
  return { accessToken: undefined };
}

export const CreateAccessResponse: MessageFns<CreateAccessResponse> = {
  encode(message: CreateAccessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== undefined) {
      Access.encode(message.accessToken, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAccessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAccessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = Access.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateAccessResponse {
    return { accessToken: isSet(object.accessToken) ? Access.fromJSON(object.accessToken) : undefined };
  },

  toJSON(message: CreateAccessResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== undefined) {
      obj.accessToken = Access.toJSON(message.accessToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateAccessResponse>, I>>(base?: I): CreateAccessResponse {
    return CreateAccessResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateAccessResponse>, I>>(object: I): CreateAccessResponse {
    const message = createBaseCreateAccessResponse();
    message.accessToken = (object.accessToken !== undefined && object.accessToken !== null)
      ? Access.fromPartial(object.accessToken)
      : undefined;
    return message;
  },
};

function createBaseDeleteAccessRequest(): DeleteAccessRequest {
  return { id: "", tenantId: "" };
}

export const DeleteAccessRequest: MessageFns<DeleteAccessRequest> = {
  encode(message: DeleteAccessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAccessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccessRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
    };
  },

  toJSON(message: DeleteAccessRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccessRequest>, I>>(base?: I): DeleteAccessRequest {
    return DeleteAccessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccessRequest>, I>>(object: I): DeleteAccessRequest {
    const message = createBaseDeleteAccessRequest();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    return message;
  },
};

function createBaseDeleteAccessResponse(): DeleteAccessResponse {
  return { accessToken: undefined };
}

export const DeleteAccessResponse: MessageFns<DeleteAccessResponse> = {
  encode(message: DeleteAccessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== undefined) {
      Access.encode(message.accessToken, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteAccessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteAccessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = Access.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteAccessResponse {
    return { accessToken: isSet(object.accessToken) ? Access.fromJSON(object.accessToken) : undefined };
  },

  toJSON(message: DeleteAccessResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== undefined) {
      obj.accessToken = Access.toJSON(message.accessToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteAccessResponse>, I>>(base?: I): DeleteAccessResponse {
    return DeleteAccessResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteAccessResponse>, I>>(object: I): DeleteAccessResponse {
    const message = createBaseDeleteAccessResponse();
    message.accessToken = (object.accessToken !== undefined && object.accessToken !== null)
      ? Access.fromPartial(object.accessToken)
      : undefined;
    return message;
  },
};

function createBaseReadAccessRequest(): ReadAccessRequest {
  return { id: "", tenantId: "" };
}

export const ReadAccessRequest: MessageFns<ReadAccessRequest> = {
  encode(message: ReadAccessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadAccessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadAccessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadAccessRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
    };
  },

  toJSON(message: ReadAccessRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadAccessRequest>, I>>(base?: I): ReadAccessRequest {
    return ReadAccessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadAccessRequest>, I>>(object: I): ReadAccessRequest {
    const message = createBaseReadAccessRequest();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    return message;
  },
};

function createBaseReadAccessResponse(): ReadAccessResponse {
  return { accessToken: undefined };
}

export const ReadAccessResponse: MessageFns<ReadAccessResponse> = {
  encode(message: ReadAccessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accessToken !== undefined) {
      Access.encode(message.accessToken, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadAccessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadAccessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = Access.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadAccessResponse {
    return { accessToken: isSet(object.accessToken) ? Access.fromJSON(object.accessToken) : undefined };
  },

  toJSON(message: ReadAccessResponse): unknown {
    const obj: any = {};
    if (message.accessToken !== undefined) {
      obj.accessToken = Access.toJSON(message.accessToken);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadAccessResponse>, I>>(base?: I): ReadAccessResponse {
    return ReadAccessResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadAccessResponse>, I>>(object: I): ReadAccessResponse {
    const message = createBaseReadAccessResponse();
    message.accessToken = (object.accessToken !== undefined && object.accessToken !== null)
      ? Access.fromPartial(object.accessToken)
      : undefined;
    return message;
  },
};

function createBaseFindAccessRequest(): FindAccessRequest {
  return { filter: "", tenantId: "" };
}

export const FindAccessRequest: MessageFns<FindAccessRequest> = {
  encode(message: FindAccessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== "") {
      writer.uint32(10).string(message.filter);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindAccessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindAccessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindAccessRequest {
    return {
      filter: isSet(object.filter) ? globalThis.String(object.filter) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
    };
  },

  toJSON(message: FindAccessRequest): unknown {
    const obj: any = {};
    if (message.filter !== "") {
      obj.filter = message.filter;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindAccessRequest>, I>>(base?: I): FindAccessRequest {
    return FindAccessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindAccessRequest>, I>>(object: I): FindAccessRequest {
    const message = createBaseFindAccessRequest();
    message.filter = object.filter ?? "";
    message.tenantId = object.tenantId ?? "";
    return message;
  },
};

function createBaseFindAccessResponse(): FindAccessResponse {
  return { accessToken: [] };
}

export const FindAccessResponse: MessageFns<FindAccessResponse> = {
  encode(message: FindAccessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.accessToken) {
      Access.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindAccessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindAccessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken.push(Access.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindAccessResponse {
    return {
      accessToken: globalThis.Array.isArray(object?.accessToken)
        ? object.accessToken.map((e: any) => Access.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FindAccessResponse): unknown {
    const obj: any = {};
    if (message.accessToken?.length) {
      obj.accessToken = message.accessToken.map((e) => Access.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindAccessResponse>, I>>(base?: I): FindAccessResponse {
    return FindAccessResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindAccessResponse>, I>>(object: I): FindAccessResponse {
    const message = createBaseFindAccessResponse();
    message.accessToken = object.accessToken?.map((e) => Access.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHasRightsRequest(): HasRightsRequest {
  return { token: "", scope: "", tenantId: "" };
}

export const HasRightsRequest: MessageFns<HasRightsRequest> = {
  encode(message: HasRightsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.scope !== "") {
      writer.uint32(18).string(message.scope);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasRightsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasRightsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasRightsRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
    };
  },

  toJSON(message: HasRightsRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasRightsRequest>, I>>(base?: I): HasRightsRequest {
    return HasRightsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasRightsRequest>, I>>(object: I): HasRightsRequest {
    const message = createBaseHasRightsRequest();
    message.token = object.token ?? "";
    message.scope = object.scope ?? "";
    message.tenantId = object.tenantId ?? "";
    return message;
  },
};

function createBaseHasRightsResponse(): HasRightsResponse {
  return { access: false };
}

export const HasRightsResponse: MessageFns<HasRightsResponse> = {
  encode(message: HasRightsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access !== false) {
      writer.uint32(8).bool(message.access);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasRightsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasRightsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.access = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasRightsResponse {
    return { access: isSet(object.access) ? globalThis.Boolean(object.access) : false };
  },

  toJSON(message: HasRightsResponse): unknown {
    const obj: any = {};
    if (message.access !== false) {
      obj.access = message.access;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasRightsResponse>, I>>(base?: I): HasRightsResponse {
    return HasRightsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasRightsResponse>, I>>(object: I): HasRightsResponse {
    const message = createBaseHasRightsResponse();
    message.access = object.access ?? false;
    return message;
  },
};

export interface AccessService {
  CreateAccess(request: CreateAccessRequest): Promise<CreateAccessResponse>;
  DeleteAccess(request: DeleteAccessRequest): Promise<DeleteAccessResponse>;
  ReadAccess(request: ReadAccessRequest): Promise<ReadAccessResponse>;
  FindAccess(request: FindAccessRequest): Promise<FindAccessResponse>;
  HasRights(request: HasRightsRequest): Promise<HasRightsResponse>;
}

export const AccessServiceServiceName = "io.ultimatebackend.srv.access.AccessService";
export class AccessServiceClientImpl implements AccessService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AccessServiceServiceName;
    this.rpc = rpc;
    this.CreateAccess = this.CreateAccess.bind(this);
    this.DeleteAccess = this.DeleteAccess.bind(this);
    this.ReadAccess = this.ReadAccess.bind(this);
    this.FindAccess = this.FindAccess.bind(this);
    this.HasRights = this.HasRights.bind(this);
  }
  CreateAccess(request: CreateAccessRequest): Promise<CreateAccessResponse> {
    const data = CreateAccessRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateAccess", data);
    return promise.then((data) => CreateAccessResponse.decode(new BinaryReader(data)));
  }

  DeleteAccess(request: DeleteAccessRequest): Promise<DeleteAccessResponse> {
    const data = DeleteAccessRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteAccess", data);
    return promise.then((data) => DeleteAccessResponse.decode(new BinaryReader(data)));
  }

  ReadAccess(request: ReadAccessRequest): Promise<ReadAccessResponse> {
    const data = ReadAccessRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ReadAccess", data);
    return promise.then((data) => ReadAccessResponse.decode(new BinaryReader(data)));
  }

  FindAccess(request: FindAccessRequest): Promise<FindAccessResponse> {
    const data = FindAccessRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindAccess", data);
    return promise.then((data) => FindAccessResponse.decode(new BinaryReader(data)));
  }

  HasRights(request: HasRightsRequest): Promise<HasRightsResponse> {
    const data = HasRightsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "HasRights", data);
    return promise.then((data) => HasRightsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
