// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/account.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'io.ultimatebackend.srv.account';

export enum LoginServiceTypes {
  Password = 0,
  Facebook = 1,
  Github = 2,
  Google = 3,
  UNRECOGNIZED = -1,
}

export function loginServiceTypesFromJSON(object: any): LoginServiceTypes {
  switch (object) {
    case 0:
    case 'Password':
      return LoginServiceTypes.Password;
    case 1:
    case 'Facebook':
      return LoginServiceTypes.Facebook;
    case 2:
    case 'Github':
      return LoginServiceTypes.Github;
    case 3:
    case 'Google':
      return LoginServiceTypes.Google;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return LoginServiceTypes.UNRECOGNIZED;
  }
}

export function loginServiceTypesToJSON(object: LoginServiceTypes): string {
  switch (object) {
    case LoginServiceTypes.Password:
      return 'Password';
    case LoginServiceTypes.Facebook:
      return 'Facebook';
    case LoginServiceTypes.Github:
      return 'Github';
    case LoginServiceTypes.Google:
      return 'Google';
    case LoginServiceTypes.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export interface PasswordStruct {
  /** @inject_tag: bson:"hashed,omitempty" */
  hashed: string;
}

export interface AuthServices {
  /** @inject_tag: bson:"password,omitempty" */
  password: PasswordStruct | undefined;
}

export interface EmailObject {
  /** @inject_tag: bson:"address,omitempty" */
  address: string;
  /** @inject_tag: bson:"verified,omitempty" */
  verified: boolean;
  /** @inject_tag: bson:"primary,omitempty" */
  primary: boolean;
  /** @inject_tag: bson:"verificationCode" */
  verificationCode: string;
}

export interface User {
  /** @inject_tag: bson:"_id,omitempty" */
  id: string;
  /** @inject_tag: bson:"username,omitempty" */
  username: string;
  /** @inject_tag: bson:"primaryEmail,omitempty" */
  primaryEmail: string;
  /** @inject_tag: bson:"firstname,omitempty" */
  firstname: string;
  /** @inject_tag: bson:"lastname,omitempty" */
  lastname: string;
  /** @inject_tag: bson:"createdAt,omitempty" */
  createdAt: string;
  /** @inject_tag: bson:"updatedAt,omitempty" */
  updatedAt: string;
  /** @inject_tag: bson:"emails,omitempty" */
  emails: EmailObject[];
  /** @inject_tag: bson:"services,omitempty" */
  services: AuthServices | undefined;
  /** @inject_tag: bson:"settings,omitempty" */
  settings: Settings | undefined;
}

export interface Settings {
  stripeId: string;
}

export interface Session {
  id: string;
  email: string;
  /** unix */
  created: number;
  /** unix */
  expires: number;
}

export interface CreateRequest {
  username: string;
  password: string;
  email: string;
  firstname: string;
  lastname: string;
  service: LoginServiceTypes;
  tokens: { [key: string]: string };
}

export interface CreateRequest_TokensEntry {
  key: string;
  value: string;
}

export interface CreateResponse {
  activationLink: string;
}

export interface DeleteRequest {
  id: string;
}

export interface DeleteResponse {
  success: boolean;
}

export interface ReadRequest {
  query: string;
}

export interface ReadResponse {
  user: User | undefined;
}

export interface UpdateRequest {
  user: User | undefined;
}

export interface UpdateResponse {
  user: User | undefined;
}

export interface UpdatePasswordRequest {
  userId: string;
  oldPassword: string;
  newPassword: string;
  confirmPassword: string;
}

export interface UpdatePasswordResponse {
  success: boolean;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface ForgotPasswordResponse {
  success: boolean;
}

export interface SearchRequest {
  username: string;
  email: string;
  limit: number;
  offset: number;
}

export interface SearchResponse {
  users: User[];
}

export interface ReadSessionRequest {
  sessionId: string;
}

export interface ReadSessionResponse {
  session: Session | undefined;
}

export interface LoginTypeParams {
  accessToken: string;
  userId: string;
  password: string;
  email: string;
}

export interface LoginRequest {
  service: LoginServiceTypes;
  params: LoginTypeParams | undefined;
}

export interface LoginResponse {
  session: Session | undefined;
  user: User | undefined;
}

export interface LogoutRequest {
  sessionId: string;
}

export interface LogoutResponse {
  success: boolean;
}

export interface VerifyAccountRequest {
  email: string;
  pincode: string;
}

export interface VerifyAccountResponse {
  success: boolean;
}

export interface VerifyActivationLinkRequest {
  token: string;
}

export interface VerifyActivationLinkResponse {
  email: string;
  pincode: string;
}

export interface ResendVerificationCodeRequest {
  email: string;
}

export interface ResendVerificationCodeResponse {
  success: boolean;
}

function createBasePasswordStruct(): PasswordStruct {
  return { hashed: '' };
}

export const PasswordStruct: MessageFns<PasswordStruct> = {
  encode(
    message: PasswordStruct,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.hashed !== '') {
      writer.uint32(10).string(message.hashed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PasswordStruct {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePasswordStruct();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hashed = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PasswordStruct {
    return {
      hashed: isSet(object.hashed) ? globalThis.String(object.hashed) : '',
    };
  },

  toJSON(message: PasswordStruct): unknown {
    const obj: any = {};
    if (message.hashed !== '') {
      obj.hashed = message.hashed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PasswordStruct>, I>>(
    base?: I,
  ): PasswordStruct {
    return PasswordStruct.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PasswordStruct>, I>>(
    object: I,
  ): PasswordStruct {
    const message = createBasePasswordStruct();
    message.hashed = object.hashed ?? '';
    return message;
  },
};

function createBaseAuthServices(): AuthServices {
  return { password: undefined };
}

export const AuthServices: MessageFns<AuthServices> = {
  encode(
    message: AuthServices,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.password !== undefined) {
      PasswordStruct.encode(message.password, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthServices {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthServices();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.password = PasswordStruct.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthServices {
    return {
      password: isSet(object.password)
        ? PasswordStruct.fromJSON(object.password)
        : undefined,
    };
  },

  toJSON(message: AuthServices): unknown {
    const obj: any = {};
    if (message.password !== undefined) {
      obj.password = PasswordStruct.toJSON(message.password);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthServices>, I>>(
    base?: I,
  ): AuthServices {
    return AuthServices.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthServices>, I>>(
    object: I,
  ): AuthServices {
    const message = createBaseAuthServices();
    message.password =
      object.password !== undefined && object.password !== null
        ? PasswordStruct.fromPartial(object.password)
        : undefined;
    return message;
  },
};

function createBaseEmailObject(): EmailObject {
  return { address: '', verified: false, primary: false, verificationCode: '' };
}

export const EmailObject: MessageFns<EmailObject> = {
  encode(
    message: EmailObject,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.address !== '') {
      writer.uint32(10).string(message.address);
    }
    if (message.verified !== false) {
      writer.uint32(16).bool(message.verified);
    }
    if (message.primary !== false) {
      writer.uint32(24).bool(message.primary);
    }
    if (message.verificationCode !== '') {
      writer.uint32(34).string(message.verificationCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailObject {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.verified = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.primary = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.verificationCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailObject {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : '',
      verified: isSet(object.verified)
        ? globalThis.Boolean(object.verified)
        : false,
      primary: isSet(object.primary)
        ? globalThis.Boolean(object.primary)
        : false,
      verificationCode: isSet(object.verificationCode)
        ? globalThis.String(object.verificationCode)
        : '',
    };
  },

  toJSON(message: EmailObject): unknown {
    const obj: any = {};
    if (message.address !== '') {
      obj.address = message.address;
    }
    if (message.verified !== false) {
      obj.verified = message.verified;
    }
    if (message.primary !== false) {
      obj.primary = message.primary;
    }
    if (message.verificationCode !== '') {
      obj.verificationCode = message.verificationCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailObject>, I>>(base?: I): EmailObject {
    return EmailObject.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailObject>, I>>(
    object: I,
  ): EmailObject {
    const message = createBaseEmailObject();
    message.address = object.address ?? '';
    message.verified = object.verified ?? false;
    message.primary = object.primary ?? false;
    message.verificationCode = object.verificationCode ?? '';
    return message;
  },
};

function createBaseUser(): User {
  return {
    id: '',
    username: '',
    primaryEmail: '',
    firstname: '',
    lastname: '',
    createdAt: '',
    updatedAt: '',
    emails: [],
    services: undefined,
    settings: undefined,
  };
}

export const User: MessageFns<User> = {
  encode(
    message: User,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.username !== '') {
      writer.uint32(18).string(message.username);
    }
    if (message.primaryEmail !== '') {
      writer.uint32(26).string(message.primaryEmail);
    }
    if (message.firstname !== '') {
      writer.uint32(34).string(message.firstname);
    }
    if (message.lastname !== '') {
      writer.uint32(42).string(message.lastname);
    }
    if (message.createdAt !== '') {
      writer.uint32(50).string(message.createdAt);
    }
    if (message.updatedAt !== '') {
      writer.uint32(58).string(message.updatedAt);
    }
    for (const v of message.emails) {
      EmailObject.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.services !== undefined) {
      AuthServices.encode(message.services, writer.uint32(74).fork()).join();
    }
    if (message.settings !== undefined) {
      Settings.encode(message.settings, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.primaryEmail = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstname = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastname = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.emails.push(EmailObject.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.services = AuthServices.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.settings = Settings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      username: isSet(object.username)
        ? globalThis.String(object.username)
        : '',
      primaryEmail: isSet(object.primaryEmail)
        ? globalThis.String(object.primaryEmail)
        : '',
      firstname: isSet(object.firstname)
        ? globalThis.String(object.firstname)
        : '',
      lastname: isSet(object.lastname)
        ? globalThis.String(object.lastname)
        : '',
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : '',
      emails: globalThis.Array.isArray(object?.emails)
        ? object.emails.map((e: any) => EmailObject.fromJSON(e))
        : [],
      services: isSet(object.services)
        ? AuthServices.fromJSON(object.services)
        : undefined,
      settings: isSet(object.settings)
        ? Settings.fromJSON(object.settings)
        : undefined,
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.username !== '') {
      obj.username = message.username;
    }
    if (message.primaryEmail !== '') {
      obj.primaryEmail = message.primaryEmail;
    }
    if (message.firstname !== '') {
      obj.firstname = message.firstname;
    }
    if (message.lastname !== '') {
      obj.lastname = message.lastname;
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== '') {
      obj.updatedAt = message.updatedAt;
    }
    if (message.emails?.length) {
      obj.emails = message.emails.map((e) => EmailObject.toJSON(e));
    }
    if (message.services !== undefined) {
      obj.services = AuthServices.toJSON(message.services);
    }
    if (message.settings !== undefined) {
      obj.settings = Settings.toJSON(message.settings);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? '';
    message.username = object.username ?? '';
    message.primaryEmail = object.primaryEmail ?? '';
    message.firstname = object.firstname ?? '';
    message.lastname = object.lastname ?? '';
    message.createdAt = object.createdAt ?? '';
    message.updatedAt = object.updatedAt ?? '';
    message.emails =
      object.emails?.map((e) => EmailObject.fromPartial(e)) || [];
    message.services =
      object.services !== undefined && object.services !== null
        ? AuthServices.fromPartial(object.services)
        : undefined;
    message.settings =
      object.settings !== undefined && object.settings !== null
        ? Settings.fromPartial(object.settings)
        : undefined;
    return message;
  },
};

function createBaseSettings(): Settings {
  return { stripeId: '' };
}

export const Settings: MessageFns<Settings> = {
  encode(
    message: Settings,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.stripeId !== '') {
      writer.uint32(10).string(message.stripeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Settings {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stripeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Settings {
    return {
      stripeId: isSet(object.stripeId)
        ? globalThis.String(object.stripeId)
        : '',
    };
  },

  toJSON(message: Settings): unknown {
    const obj: any = {};
    if (message.stripeId !== '') {
      obj.stripeId = message.stripeId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Settings>, I>>(base?: I): Settings {
    return Settings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Settings>, I>>(object: I): Settings {
    const message = createBaseSettings();
    message.stripeId = object.stripeId ?? '';
    return message;
  },
};

function createBaseSession(): Session {
  return { id: '', email: '', created: 0, expires: 0 };
}

export const Session: MessageFns<Session> = {
  encode(
    message: Session,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== '') {
      writer.uint32(18).string(message.email);
    }
    if (message.created !== 0) {
      writer.uint32(24).int32(message.created);
    }
    if (message.expires !== 0) {
      writer.uint32(32).int32(message.expires);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.created = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expires = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      created: isSet(object.created) ? globalThis.Number(object.created) : 0,
      expires: isSet(object.expires) ? globalThis.Number(object.expires) : 0,
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.created !== 0) {
      obj.created = Math.round(message.created);
    }
    if (message.expires !== 0) {
      obj.expires = Math.round(message.expires);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.id = object.id ?? '';
    message.email = object.email ?? '';
    message.created = object.created ?? 0;
    message.expires = object.expires ?? 0;
    return message;
  },
};

function createBaseCreateRequest(): CreateRequest {
  return {
    username: '',
    password: '',
    email: '',
    firstname: '',
    lastname: '',
    service: 0,
    tokens: {},
  };
}

export const CreateRequest: MessageFns<CreateRequest> = {
  encode(
    message: CreateRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.username !== '') {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== '') {
      writer.uint32(18).string(message.password);
    }
    if (message.email !== '') {
      writer.uint32(26).string(message.email);
    }
    if (message.firstname !== '') {
      writer.uint32(34).string(message.firstname);
    }
    if (message.lastname !== '') {
      writer.uint32(42).string(message.lastname);
    }
    if (message.service !== 0) {
      writer.uint32(48).int32(message.service);
    }
    Object.entries(message.tokens).forEach(([key, value]) => {
      CreateRequest_TokensEntry.encode(
        { key: key as any, value },
        writer.uint32(58).fork(),
      ).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstname = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastname = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.service = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = CreateRequest_TokensEntry.decode(
            reader,
            reader.uint32(),
          );
          if (entry7.value !== undefined) {
            message.tokens[entry7.key] = entry7.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRequest {
    return {
      username: isSet(object.username)
        ? globalThis.String(object.username)
        : '',
      password: isSet(object.password)
        ? globalThis.String(object.password)
        : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      firstname: isSet(object.firstname)
        ? globalThis.String(object.firstname)
        : '',
      lastname: isSet(object.lastname)
        ? globalThis.String(object.lastname)
        : '',
      service: isSet(object.service)
        ? loginServiceTypesFromJSON(object.service)
        : 0,
      tokens: isObject(object.tokens)
        ? Object.entries(object.tokens).reduce<{ [key: string]: string }>(
            (acc, [key, value]) => {
              acc[key] = String(value);
              return acc;
            },
            {},
          )
        : {},
    };
  },

  toJSON(message: CreateRequest): unknown {
    const obj: any = {};
    if (message.username !== '') {
      obj.username = message.username;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.firstname !== '') {
      obj.firstname = message.firstname;
    }
    if (message.lastname !== '') {
      obj.lastname = message.lastname;
    }
    if (message.service !== 0) {
      obj.service = loginServiceTypesToJSON(message.service);
    }
    if (message.tokens) {
      const entries = Object.entries(message.tokens);
      if (entries.length > 0) {
        obj.tokens = {};
        entries.forEach(([k, v]) => {
          obj.tokens[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateRequest>, I>>(
    base?: I,
  ): CreateRequest {
    return CreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateRequest>, I>>(
    object: I,
  ): CreateRequest {
    const message = createBaseCreateRequest();
    message.username = object.username ?? '';
    message.password = object.password ?? '';
    message.email = object.email ?? '';
    message.firstname = object.firstname ?? '';
    message.lastname = object.lastname ?? '';
    message.service = object.service ?? 0;
    message.tokens = Object.entries(object.tokens ?? {}).reduce<{
      [key: string]: string;
    }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseCreateRequest_TokensEntry(): CreateRequest_TokensEntry {
  return { key: '', value: '' };
}

export const CreateRequest_TokensEntry: MessageFns<CreateRequest_TokensEntry> =
  {
    encode(
      message: CreateRequest_TokensEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.key !== '') {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== '') {
        writer.uint32(18).string(message.value);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): CreateRequest_TokensEntry {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateRequest_TokensEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): CreateRequest_TokensEntry {
      return {
        key: isSet(object.key) ? globalThis.String(object.key) : '',
        value: isSet(object.value) ? globalThis.String(object.value) : '',
      };
    },

    toJSON(message: CreateRequest_TokensEntry): unknown {
      const obj: any = {};
      if (message.key !== '') {
        obj.key = message.key;
      }
      if (message.value !== '') {
        obj.value = message.value;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<CreateRequest_TokensEntry>, I>>(
      base?: I,
    ): CreateRequest_TokensEntry {
      return CreateRequest_TokensEntry.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<CreateRequest_TokensEntry>, I>>(
      object: I,
    ): CreateRequest_TokensEntry {
      const message = createBaseCreateRequest_TokensEntry();
      message.key = object.key ?? '';
      message.value = object.value ?? '';
      return message;
    },
  };

function createBaseCreateResponse(): CreateResponse {
  return { activationLink: '' };
}

export const CreateResponse: MessageFns<CreateResponse> = {
  encode(
    message: CreateResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.activationLink !== '') {
      writer.uint32(10).string(message.activationLink);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.activationLink = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateResponse {
    return {
      activationLink: isSet(object.activationLink)
        ? globalThis.String(object.activationLink)
        : '',
    };
  },

  toJSON(message: CreateResponse): unknown {
    const obj: any = {};
    if (message.activationLink !== '') {
      obj.activationLink = message.activationLink;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateResponse>, I>>(
    base?: I,
  ): CreateResponse {
    return CreateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateResponse>, I>>(
    object: I,
  ): CreateResponse {
    const message = createBaseCreateResponse();
    message.activationLink = object.activationLink ?? '';
    return message;
  },
};

function createBaseDeleteRequest(): DeleteRequest {
  return { id: '' };
}

export const DeleteRequest: MessageFns<DeleteRequest> = {
  encode(
    message: DeleteRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: DeleteRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteRequest>, I>>(
    base?: I,
  ): DeleteRequest {
    return DeleteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteRequest>, I>>(
    object: I,
  ): DeleteRequest {
    const message = createBaseDeleteRequest();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseDeleteResponse(): DeleteResponse {
  return { success: false };
}

export const DeleteResponse: MessageFns<DeleteResponse> = {
  encode(
    message: DeleteResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: DeleteResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteResponse>, I>>(
    base?: I,
  ): DeleteResponse {
    return DeleteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteResponse>, I>>(
    object: I,
  ): DeleteResponse {
    const message = createBaseDeleteResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseReadRequest(): ReadRequest {
  return { query: '' };
}

export const ReadRequest: MessageFns<ReadRequest> = {
  encode(
    message: ReadRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.query !== '') {
      writer.uint32(42).string(message.query);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.query = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : '',
    };
  },

  toJSON(message: ReadRequest): unknown {
    const obj: any = {};
    if (message.query !== '') {
      obj.query = message.query;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadRequest>, I>>(base?: I): ReadRequest {
    return ReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadRequest>, I>>(
    object: I,
  ): ReadRequest {
    const message = createBaseReadRequest();
    message.query = object.query ?? '';
    return message;
  },
};

function createBaseReadResponse(): ReadResponse {
  return { user: undefined };
}

export const ReadResponse: MessageFns<ReadResponse> = {
  encode(
    message: ReadResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadResponse {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: ReadResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadResponse>, I>>(
    base?: I,
  ): ReadResponse {
    return ReadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadResponse>, I>>(
    object: I,
  ): ReadResponse {
    const message = createBaseReadResponse();
    message.user =
      object.user !== undefined && object.user !== null
        ? User.fromPartial(object.user)
        : undefined;
    return message;
  },
};

function createBaseUpdateRequest(): UpdateRequest {
  return { user: undefined };
}

export const UpdateRequest: MessageFns<UpdateRequest> = {
  encode(
    message: UpdateRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateRequest {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: UpdateRequest): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateRequest>, I>>(
    base?: I,
  ): UpdateRequest {
    return UpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateRequest>, I>>(
    object: I,
  ): UpdateRequest {
    const message = createBaseUpdateRequest();
    message.user =
      object.user !== undefined && object.user !== null
        ? User.fromPartial(object.user)
        : undefined;
    return message;
  },
};

function createBaseUpdateResponse(): UpdateResponse {
  return { user: undefined };
}

export const UpdateResponse: MessageFns<UpdateResponse> = {
  encode(
    message: UpdateResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateResponse {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: UpdateResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateResponse>, I>>(
    base?: I,
  ): UpdateResponse {
    return UpdateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateResponse>, I>>(
    object: I,
  ): UpdateResponse {
    const message = createBaseUpdateResponse();
    message.user =
      object.user !== undefined && object.user !== null
        ? User.fromPartial(object.user)
        : undefined;
    return message;
  },
};

function createBaseUpdatePasswordRequest(): UpdatePasswordRequest {
  return { userId: '', oldPassword: '', newPassword: '', confirmPassword: '' };
}

export const UpdatePasswordRequest: MessageFns<UpdatePasswordRequest> = {
  encode(
    message: UpdatePasswordRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId);
    }
    if (message.oldPassword !== '') {
      writer.uint32(18).string(message.oldPassword);
    }
    if (message.newPassword !== '') {
      writer.uint32(26).string(message.newPassword);
    }
    if (message.confirmPassword !== '') {
      writer.uint32(34).string(message.confirmPassword);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdatePasswordRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.oldPassword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.confirmPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePasswordRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      oldPassword: isSet(object.oldPassword)
        ? globalThis.String(object.oldPassword)
        : '',
      newPassword: isSet(object.newPassword)
        ? globalThis.String(object.newPassword)
        : '',
      confirmPassword: isSet(object.confirmPassword)
        ? globalThis.String(object.confirmPassword)
        : '',
    };
  },

  toJSON(message: UpdatePasswordRequest): unknown {
    const obj: any = {};
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.oldPassword !== '') {
      obj.oldPassword = message.oldPassword;
    }
    if (message.newPassword !== '') {
      obj.newPassword = message.newPassword;
    }
    if (message.confirmPassword !== '') {
      obj.confirmPassword = message.confirmPassword;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePasswordRequest>, I>>(
    base?: I,
  ): UpdatePasswordRequest {
    return UpdatePasswordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePasswordRequest>, I>>(
    object: I,
  ): UpdatePasswordRequest {
    const message = createBaseUpdatePasswordRequest();
    message.userId = object.userId ?? '';
    message.oldPassword = object.oldPassword ?? '';
    message.newPassword = object.newPassword ?? '';
    message.confirmPassword = object.confirmPassword ?? '';
    return message;
  },
};

function createBaseUpdatePasswordResponse(): UpdatePasswordResponse {
  return { success: false };
}

export const UpdatePasswordResponse: MessageFns<UpdatePasswordResponse> = {
  encode(
    message: UpdatePasswordResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdatePasswordResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePasswordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePasswordResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: UpdatePasswordResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePasswordResponse>, I>>(
    base?: I,
  ): UpdatePasswordResponse {
    return UpdatePasswordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePasswordResponse>, I>>(
    object: I,
  ): UpdatePasswordResponse {
    const message = createBaseUpdatePasswordResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseForgotPasswordRequest(): ForgotPasswordRequest {
  return { email: '' };
}

export const ForgotPasswordRequest: MessageFns<ForgotPasswordRequest> = {
  encode(
    message: ForgotPasswordRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.email !== '') {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ForgotPasswordRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseForgotPasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ForgotPasswordRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : '',
    };
  },

  toJSON(message: ForgotPasswordRequest): unknown {
    const obj: any = {};
    if (message.email !== '') {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForgotPasswordRequest>, I>>(
    base?: I,
  ): ForgotPasswordRequest {
    return ForgotPasswordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForgotPasswordRequest>, I>>(
    object: I,
  ): ForgotPasswordRequest {
    const message = createBaseForgotPasswordRequest();
    message.email = object.email ?? '';
    return message;
  },
};

function createBaseForgotPasswordResponse(): ForgotPasswordResponse {
  return { success: false };
}

export const ForgotPasswordResponse: MessageFns<ForgotPasswordResponse> = {
  encode(
    message: ForgotPasswordResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ForgotPasswordResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseForgotPasswordResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ForgotPasswordResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: ForgotPasswordResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForgotPasswordResponse>, I>>(
    base?: I,
  ): ForgotPasswordResponse {
    return ForgotPasswordResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForgotPasswordResponse>, I>>(
    object: I,
  ): ForgotPasswordResponse {
    const message = createBaseForgotPasswordResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseSearchRequest(): SearchRequest {
  return { username: '', email: '', limit: 0, offset: 0 };
}

export const SearchRequest: MessageFns<SearchRequest> = {
  encode(
    message: SearchRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.username !== '') {
      writer.uint32(10).string(message.username);
    }
    if (message.email !== '') {
      writer.uint32(18).string(message.email);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchRequest {
    return {
      username: isSet(object.username)
        ? globalThis.String(object.username)
        : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: SearchRequest): unknown {
    const obj: any = {};
    if (message.username !== '') {
      obj.username = message.username;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchRequest>, I>>(
    base?: I,
  ): SearchRequest {
    return SearchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchRequest>, I>>(
    object: I,
  ): SearchRequest {
    const message = createBaseSearchRequest();
    message.username = object.username ?? '';
    message.email = object.email ?? '';
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseSearchResponse(): SearchResponse {
  return { users: [] };
}

export const SearchResponse: MessageFns<SearchResponse> = {
  encode(
    message: SearchResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.users) {
      User.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.users.push(User.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchResponse {
    return {
      users: globalThis.Array.isArray(object?.users)
        ? object.users.map((e: any) => User.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SearchResponse): unknown {
    const obj: any = {};
    if (message.users?.length) {
      obj.users = message.users.map((e) => User.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchResponse>, I>>(
    base?: I,
  ): SearchResponse {
    return SearchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchResponse>, I>>(
    object: I,
  ): SearchResponse {
    const message = createBaseSearchResponse();
    message.users = object.users?.map((e) => User.fromPartial(e)) || [];
    return message;
  },
};

function createBaseReadSessionRequest(): ReadSessionRequest {
  return { sessionId: '' };
}

export const ReadSessionRequest: MessageFns<ReadSessionRequest> = {
  encode(
    message: ReadSessionRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.sessionId !== '') {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadSessionRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadSessionRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : '',
    };
  },

  toJSON(message: ReadSessionRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== '') {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadSessionRequest>, I>>(
    base?: I,
  ): ReadSessionRequest {
    return ReadSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadSessionRequest>, I>>(
    object: I,
  ): ReadSessionRequest {
    const message = createBaseReadSessionRequest();
    message.sessionId = object.sessionId ?? '';
    return message;
  },
};

function createBaseReadSessionResponse(): ReadSessionResponse {
  return { session: undefined };
}

export const ReadSessionResponse: MessageFns<ReadSessionResponse> = {
  encode(
    message: ReadSessionResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadSessionResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadSessionResponse {
    return {
      session: isSet(object.session)
        ? Session.fromJSON(object.session)
        : undefined,
    };
  },

  toJSON(message: ReadSessionResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadSessionResponse>, I>>(
    base?: I,
  ): ReadSessionResponse {
    return ReadSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadSessionResponse>, I>>(
    object: I,
  ): ReadSessionResponse {
    const message = createBaseReadSessionResponse();
    message.session =
      object.session !== undefined && object.session !== null
        ? Session.fromPartial(object.session)
        : undefined;
    return message;
  },
};

function createBaseLoginTypeParams(): LoginTypeParams {
  return { accessToken: '', userId: '', password: '', email: '' };
}

export const LoginTypeParams: MessageFns<LoginTypeParams> = {
  encode(
    message: LoginTypeParams,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.accessToken !== '') {
      writer.uint32(10).string(message.accessToken);
    }
    if (message.userId !== '') {
      writer.uint32(18).string(message.userId);
    }
    if (message.password !== '') {
      writer.uint32(26).string(message.password);
    }
    if (message.email !== '') {
      writer.uint32(34).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginTypeParams {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginTypeParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginTypeParams {
    return {
      accessToken: isSet(object.accessToken)
        ? globalThis.String(object.accessToken)
        : '',
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      password: isSet(object.password)
        ? globalThis.String(object.password)
        : '',
      email: isSet(object.email) ? globalThis.String(object.email) : '',
    };
  },

  toJSON(message: LoginTypeParams): unknown {
    const obj: any = {};
    if (message.accessToken !== '') {
      obj.accessToken = message.accessToken;
    }
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    if (message.email !== '') {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginTypeParams>, I>>(
    base?: I,
  ): LoginTypeParams {
    return LoginTypeParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginTypeParams>, I>>(
    object: I,
  ): LoginTypeParams {
    const message = createBaseLoginTypeParams();
    message.accessToken = object.accessToken ?? '';
    message.userId = object.userId ?? '';
    message.password = object.password ?? '';
    message.email = object.email ?? '';
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { service: 0, params: undefined };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(
    message: LoginRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.service !== 0) {
      writer.uint32(8).int32(message.service);
    }
    if (message.params !== undefined) {
      LoginTypeParams.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.service = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = LoginTypeParams.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      service: isSet(object.service)
        ? loginServiceTypesFromJSON(object.service)
        : 0,
      params: isSet(object.params)
        ? LoginTypeParams.fromJSON(object.params)
        : undefined,
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.service !== 0) {
      obj.service = loginServiceTypesToJSON(message.service);
    }
    if (message.params !== undefined) {
      obj.params = LoginTypeParams.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(
    base?: I,
  ): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(
    object: I,
  ): LoginRequest {
    const message = createBaseLoginRequest();
    message.service = object.service ?? 0;
    message.params =
      object.params !== undefined && object.params !== null
        ? LoginTypeParams.fromPartial(object.params)
        : undefined;
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { session: undefined, user: undefined };
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(
    message: LoginResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResponse {
    return {
      session: isSet(object.session)
        ? Session.fromJSON(object.session)
        : undefined,
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: LoginResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(
    base?: I,
  ): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(
    object: I,
  ): LoginResponse {
    const message = createBaseLoginResponse();
    message.session =
      object.session !== undefined && object.session !== null
        ? Session.fromPartial(object.session)
        : undefined;
    message.user =
      object.user !== undefined && object.user !== null
        ? User.fromPartial(object.user)
        : undefined;
    return message;
  },
};

function createBaseLogoutRequest(): LogoutRequest {
  return { sessionId: '' };
}

export const LogoutRequest: MessageFns<LogoutRequest> = {
  encode(
    message: LogoutRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.sessionId !== '') {
      writer.uint32(10).string(message.sessionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : '',
    };
  },

  toJSON(message: LogoutRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== '') {
      obj.sessionId = message.sessionId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutRequest>, I>>(
    base?: I,
  ): LogoutRequest {
    return LogoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutRequest>, I>>(
    object: I,
  ): LogoutRequest {
    const message = createBaseLogoutRequest();
    message.sessionId = object.sessionId ?? '';
    return message;
  },
};

function createBaseLogoutResponse(): LogoutResponse {
  return { success: false };
}

export const LogoutResponse: MessageFns<LogoutResponse> = {
  encode(
    message: LogoutResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: LogoutResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutResponse>, I>>(
    base?: I,
  ): LogoutResponse {
    return LogoutResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutResponse>, I>>(
    object: I,
  ): LogoutResponse {
    const message = createBaseLogoutResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseVerifyAccountRequest(): VerifyAccountRequest {
  return { email: '', pincode: '' };
}

export const VerifyAccountRequest: MessageFns<VerifyAccountRequest> = {
  encode(
    message: VerifyAccountRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.email !== '') {
      writer.uint32(10).string(message.email);
    }
    if (message.pincode !== '') {
      writer.uint32(18).string(message.pincode);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): VerifyAccountRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyAccountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pincode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyAccountRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : '',
      pincode: isSet(object.pincode) ? globalThis.String(object.pincode) : '',
    };
  },

  toJSON(message: VerifyAccountRequest): unknown {
    const obj: any = {};
    if (message.email !== '') {
      obj.email = message.email;
    }
    if (message.pincode !== '') {
      obj.pincode = message.pincode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyAccountRequest>, I>>(
    base?: I,
  ): VerifyAccountRequest {
    return VerifyAccountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyAccountRequest>, I>>(
    object: I,
  ): VerifyAccountRequest {
    const message = createBaseVerifyAccountRequest();
    message.email = object.email ?? '';
    message.pincode = object.pincode ?? '';
    return message;
  },
};

function createBaseVerifyAccountResponse(): VerifyAccountResponse {
  return { success: false };
}

export const VerifyAccountResponse: MessageFns<VerifyAccountResponse> = {
  encode(
    message: VerifyAccountResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): VerifyAccountResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyAccountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyAccountResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: VerifyAccountResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyAccountResponse>, I>>(
    base?: I,
  ): VerifyAccountResponse {
    return VerifyAccountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyAccountResponse>, I>>(
    object: I,
  ): VerifyAccountResponse {
    const message = createBaseVerifyAccountResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseVerifyActivationLinkRequest(): VerifyActivationLinkRequest {
  return { token: '' };
}

export const VerifyActivationLinkRequest: MessageFns<VerifyActivationLinkRequest> =
  {
    encode(
      message: VerifyActivationLinkRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.token !== '') {
        writer.uint32(10).string(message.token);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): VerifyActivationLinkRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyActivationLinkRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.token = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): VerifyActivationLinkRequest {
      return {
        token: isSet(object.token) ? globalThis.String(object.token) : '',
      };
    },

    toJSON(message: VerifyActivationLinkRequest): unknown {
      const obj: any = {};
      if (message.token !== '') {
        obj.token = message.token;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<VerifyActivationLinkRequest>, I>>(
      base?: I,
    ): VerifyActivationLinkRequest {
      return VerifyActivationLinkRequest.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<VerifyActivationLinkRequest>, I>>(
      object: I,
    ): VerifyActivationLinkRequest {
      const message = createBaseVerifyActivationLinkRequest();
      message.token = object.token ?? '';
      return message;
    },
  };

function createBaseVerifyActivationLinkResponse(): VerifyActivationLinkResponse {
  return { email: '', pincode: '' };
}

export const VerifyActivationLinkResponse: MessageFns<VerifyActivationLinkResponse> =
  {
    encode(
      message: VerifyActivationLinkResponse,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.email !== '') {
        writer.uint32(10).string(message.email);
      }
      if (message.pincode !== '') {
        writer.uint32(18).string(message.pincode);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): VerifyActivationLinkResponse {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVerifyActivationLinkResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.email = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.pincode = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): VerifyActivationLinkResponse {
      return {
        email: isSet(object.email) ? globalThis.String(object.email) : '',
        pincode: isSet(object.pincode) ? globalThis.String(object.pincode) : '',
      };
    },

    toJSON(message: VerifyActivationLinkResponse): unknown {
      const obj: any = {};
      if (message.email !== '') {
        obj.email = message.email;
      }
      if (message.pincode !== '') {
        obj.pincode = message.pincode;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<VerifyActivationLinkResponse>, I>>(
      base?: I,
    ): VerifyActivationLinkResponse {
      return VerifyActivationLinkResponse.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<VerifyActivationLinkResponse>, I>>(
      object: I,
    ): VerifyActivationLinkResponse {
      const message = createBaseVerifyActivationLinkResponse();
      message.email = object.email ?? '';
      message.pincode = object.pincode ?? '';
      return message;
    },
  };

function createBaseResendVerificationCodeRequest(): ResendVerificationCodeRequest {
  return { email: '' };
}

export const ResendVerificationCodeRequest: MessageFns<ResendVerificationCodeRequest> =
  {
    encode(
      message: ResendVerificationCodeRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.email !== '') {
        writer.uint32(10).string(message.email);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ResendVerificationCodeRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseResendVerificationCodeRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.email = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): ResendVerificationCodeRequest {
      return {
        email: isSet(object.email) ? globalThis.String(object.email) : '',
      };
    },

    toJSON(message: ResendVerificationCodeRequest): unknown {
      const obj: any = {};
      if (message.email !== '') {
        obj.email = message.email;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<ResendVerificationCodeRequest>, I>>(
      base?: I,
    ): ResendVerificationCodeRequest {
      return ResendVerificationCodeRequest.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<ResendVerificationCodeRequest>, I>>(
      object: I,
    ): ResendVerificationCodeRequest {
      const message = createBaseResendVerificationCodeRequest();
      message.email = object.email ?? '';
      return message;
    },
  };

function createBaseResendVerificationCodeResponse(): ResendVerificationCodeResponse {
  return { success: false };
}

export const ResendVerificationCodeResponse: MessageFns<ResendVerificationCodeResponse> =
  {
    encode(
      message: ResendVerificationCodeResponse,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.success !== false) {
        writer.uint32(8).bool(message.success);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ResendVerificationCodeResponse {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseResendVerificationCodeResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.success = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): ResendVerificationCodeResponse {
      return {
        success: isSet(object.success)
          ? globalThis.Boolean(object.success)
          : false,
      };
    },

    toJSON(message: ResendVerificationCodeResponse): unknown {
      const obj: any = {};
      if (message.success !== false) {
        obj.success = message.success;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<ResendVerificationCodeResponse>, I>>(
      base?: I,
    ): ResendVerificationCodeResponse {
      return ResendVerificationCodeResponse.fromPartial(base ?? ({} as any));
    },
    fromPartial<
      I extends Exact<DeepPartial<ResendVerificationCodeResponse>, I>,
    >(object: I): ResendVerificationCodeResponse {
      const message = createBaseResendVerificationCodeResponse();
      message.success = object.success ?? false;
      return message;
    },
  };

export interface AccountService {
  Create(request: CreateRequest): Promise<CreateResponse>;
  Read(request: ReadRequest): Promise<ReadResponse>;
  VerifyAccount(request: VerifyAccountRequest): Promise<VerifyAccountResponse>;
  VerifyActivationLink(
    request: VerifyActivationLinkRequest,
  ): Promise<VerifyActivationLinkResponse>;
  ResendVerificationCode(
    request: ResendVerificationCodeRequest,
  ): Promise<ResendVerificationCodeResponse>;
  Update(request: UpdateRequest): Promise<UpdateResponse>;
  Delete(request: DeleteRequest): Promise<DeleteResponse>;
  Search(request: SearchRequest): Promise<SearchResponse>;
  ForgotPassword(
    request: ForgotPasswordRequest,
  ): Promise<ForgotPasswordResponse>;
  UpdatePassword(
    request: UpdatePasswordRequest,
  ): Promise<UpdatePasswordResponse>;
  Login(request: LoginRequest): Promise<LoginResponse>;
  Logout(request: LogoutRequest): Promise<LogoutResponse>;
  ReadSession(request: ReadSessionRequest): Promise<ReadSessionResponse>;
}

export const AccountServiceServiceName =
  'io.ultimatebackend.srv.account.AccountService';
export class AccountServiceClientImpl implements AccountService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AccountServiceServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.Read = this.Read.bind(this);
    this.VerifyAccount = this.VerifyAccount.bind(this);
    this.VerifyActivationLink = this.VerifyActivationLink.bind(this);
    this.ResendVerificationCode = this.ResendVerificationCode.bind(this);
    this.Update = this.Update.bind(this);
    this.Delete = this.Delete.bind(this);
    this.Search = this.Search.bind(this);
    this.ForgotPassword = this.ForgotPassword.bind(this);
    this.UpdatePassword = this.UpdatePassword.bind(this);
    this.Login = this.Login.bind(this);
    this.Logout = this.Logout.bind(this);
    this.ReadSession = this.ReadSession.bind(this);
  }
  Create(request: CreateRequest): Promise<CreateResponse> {
    const data = CreateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Create', data);
    return promise.then((data) =>
      CreateResponse.decode(new BinaryReader(data)),
    );
  }

  Read(request: ReadRequest): Promise<ReadResponse> {
    const data = ReadRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Read', data);
    return promise.then((data) => ReadResponse.decode(new BinaryReader(data)));
  }

  VerifyAccount(request: VerifyAccountRequest): Promise<VerifyAccountResponse> {
    const data = VerifyAccountRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'VerifyAccount', data);
    return promise.then((data) =>
      VerifyAccountResponse.decode(new BinaryReader(data)),
    );
  }

  VerifyActivationLink(
    request: VerifyActivationLinkRequest,
  ): Promise<VerifyActivationLinkResponse> {
    const data = VerifyActivationLinkRequest.encode(request).finish();
    const promise = this.rpc.request(
      this.service,
      'VerifyActivationLink',
      data,
    );
    return promise.then((data) =>
      VerifyActivationLinkResponse.decode(new BinaryReader(data)),
    );
  }

  ResendVerificationCode(
    request: ResendVerificationCodeRequest,
  ): Promise<ResendVerificationCodeResponse> {
    const data = ResendVerificationCodeRequest.encode(request).finish();
    const promise = this.rpc.request(
      this.service,
      'ResendVerificationCode',
      data,
    );
    return promise.then((data) =>
      ResendVerificationCodeResponse.decode(new BinaryReader(data)),
    );
  }

  Update(request: UpdateRequest): Promise<UpdateResponse> {
    const data = UpdateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Update', data);
    return promise.then((data) =>
      UpdateResponse.decode(new BinaryReader(data)),
    );
  }

  Delete(request: DeleteRequest): Promise<DeleteResponse> {
    const data = DeleteRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Delete', data);
    return promise.then((data) =>
      DeleteResponse.decode(new BinaryReader(data)),
    );
  }

  Search(request: SearchRequest): Promise<SearchResponse> {
    const data = SearchRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Search', data);
    return promise.then((data) =>
      SearchResponse.decode(new BinaryReader(data)),
    );
  }

  ForgotPassword(
    request: ForgotPasswordRequest,
  ): Promise<ForgotPasswordResponse> {
    const data = ForgotPasswordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ForgotPassword', data);
    return promise.then((data) =>
      ForgotPasswordResponse.decode(new BinaryReader(data)),
    );
  }

  UpdatePassword(
    request: UpdatePasswordRequest,
  ): Promise<UpdatePasswordResponse> {
    const data = UpdatePasswordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'UpdatePassword', data);
    return promise.then((data) =>
      UpdatePasswordResponse.decode(new BinaryReader(data)),
    );
  }

  Login(request: LoginRequest): Promise<LoginResponse> {
    const data = LoginRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Login', data);
    return promise.then((data) => LoginResponse.decode(new BinaryReader(data)));
  }

  Logout(request: LogoutRequest): Promise<LogoutResponse> {
    const data = LogoutRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Logout', data);
    return promise.then((data) =>
      LogoutResponse.decode(new BinaryReader(data)),
    );
  }

  ReadSession(request: ReadSessionRequest): Promise<ReadSessionResponse> {
    const data = ReadSessionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ReadSession', data);
    return promise.then((data) =>
      ReadSessionResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isObject(value: any): boolean {
  return typeof value === 'object' && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
