// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/project.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'io.ultimatebackend.srv.project';

export interface Paginate {
  skip: number;
  limit: number;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateProjectRequest {
  name: string;
  description: string;
}

export interface CreateProjectResponse {
  project: Project | undefined;
}

export interface UpdateProjectRequest {
  id: string;
  name: string;
  description: string;
}

export interface UpdateProjectResponse {
  project: Project | undefined;
}

export interface DeleteProjectRequest {
  id: string;
}

export interface DeleteProjectResponse {
  project: Project | undefined;
}

export interface ReadProjectRequest {
  filter: string;
}

export interface ReadProjectResponse {
  project: Project | undefined;
}

export interface FindProjectsRequest {
  filter: string;
  paginate: Paginate | undefined;
}

export interface FindProjectsResponse {
  projects: Project[];
}

function createBasePaginate(): Paginate {
  return { skip: 0, limit: 0 };
}

export const Paginate: MessageFns<Paginate> = {
  encode(
    message: Paginate,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.skip !== 0) {
      writer.uint32(8).int32(message.skip);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Paginate {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.skip = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Paginate {
    return {
      skip: isSet(object.skip) ? globalThis.Number(object.skip) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: Paginate): unknown {
    const obj: any = {};
    if (message.skip !== 0) {
      obj.skip = Math.round(message.skip);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Paginate>, I>>(base?: I): Paginate {
    return Paginate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Paginate>, I>>(object: I): Paginate {
    const message = createBasePaginate();
    message.skip = object.skip ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseProject(): Project {
  return { id: '', name: '', description: '', createdAt: '', updatedAt: '' };
}

export const Project: MessageFns<Project> = {
  encode(
    message: Project,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== '') {
      writer.uint32(26).string(message.description);
    }
    if (message.createdAt !== '') {
      writer.uint32(34).string(message.createdAt);
    }
    if (message.updatedAt !== '') {
      writer.uint32(42).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Project {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Project {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      description: isSet(object.description)
        ? globalThis.String(object.description)
        : '',
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : '',
    };
  },

  toJSON(message: Project): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.description !== '') {
      obj.description = message.description;
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== '') {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Project>, I>>(base?: I): Project {
    return Project.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Project>, I>>(object: I): Project {
    const message = createBaseProject();
    message.id = object.id ?? '';
    message.name = object.name ?? '';
    message.description = object.description ?? '';
    message.createdAt = object.createdAt ?? '';
    message.updatedAt = object.updatedAt ?? '';
    return message;
  },
};

function createBaseCreateProjectRequest(): CreateProjectRequest {
  return { name: '', description: '' };
}

export const CreateProjectRequest: MessageFns<CreateProjectRequest> = {
  encode(
    message: CreateProjectRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== '') {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateProjectRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      description: isSet(object.description)
        ? globalThis.String(object.description)
        : '',
    };
  },

  toJSON(message: CreateProjectRequest): unknown {
    const obj: any = {};
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.description !== '') {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProjectRequest>, I>>(
    base?: I,
  ): CreateProjectRequest {
    return CreateProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProjectRequest>, I>>(
    object: I,
  ): CreateProjectRequest {
    const message = createBaseCreateProjectRequest();
    message.name = object.name ?? '';
    message.description = object.description ?? '';
    return message;
  },
};

function createBaseCreateProjectResponse(): CreateProjectResponse {
  return { project: undefined };
}

export const CreateProjectResponse: MessageFns<CreateProjectResponse> = {
  encode(
    message: CreateProjectResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.project !== undefined) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateProjectResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProjectResponse {
    return {
      project: isSet(object.project)
        ? Project.fromJSON(object.project)
        : undefined,
    };
  },

  toJSON(message: CreateProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProjectResponse>, I>>(
    base?: I,
  ): CreateProjectResponse {
    return CreateProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProjectResponse>, I>>(
    object: I,
  ): CreateProjectResponse {
    const message = createBaseCreateProjectResponse();
    message.project =
      object.project !== undefined && object.project !== null
        ? Project.fromPartial(object.project)
        : undefined;
    return message;
  },
};

function createBaseUpdateProjectRequest(): UpdateProjectRequest {
  return { id: '', name: '', description: '' };
}

export const UpdateProjectRequest: MessageFns<UpdateProjectRequest> = {
  encode(
    message: UpdateProjectRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== '') {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdateProjectRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateProjectRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      description: isSet(object.description)
        ? globalThis.String(object.description)
        : '',
    };
  },

  toJSON(message: UpdateProjectRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.description !== '') {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateProjectRequest>, I>>(
    base?: I,
  ): UpdateProjectRequest {
    return UpdateProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateProjectRequest>, I>>(
    object: I,
  ): UpdateProjectRequest {
    const message = createBaseUpdateProjectRequest();
    message.id = object.id ?? '';
    message.name = object.name ?? '';
    message.description = object.description ?? '';
    return message;
  },
};

function createBaseUpdateProjectResponse(): UpdateProjectResponse {
  return { project: undefined };
}

export const UpdateProjectResponse: MessageFns<UpdateProjectResponse> = {
  encode(
    message: UpdateProjectResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.project !== undefined) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdateProjectResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateProjectResponse {
    return {
      project: isSet(object.project)
        ? Project.fromJSON(object.project)
        : undefined,
    };
  },

  toJSON(message: UpdateProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateProjectResponse>, I>>(
    base?: I,
  ): UpdateProjectResponse {
    return UpdateProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateProjectResponse>, I>>(
    object: I,
  ): UpdateProjectResponse {
    const message = createBaseUpdateProjectResponse();
    message.project =
      object.project !== undefined && object.project !== null
        ? Project.fromPartial(object.project)
        : undefined;
    return message;
  },
};

function createBaseDeleteProjectRequest(): DeleteProjectRequest {
  return { id: '' };
}

export const DeleteProjectRequest: MessageFns<DeleteProjectRequest> = {
  encode(
    message: DeleteProjectRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): DeleteProjectRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteProjectRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: DeleteProjectRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteProjectRequest>, I>>(
    base?: I,
  ): DeleteProjectRequest {
    return DeleteProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteProjectRequest>, I>>(
    object: I,
  ): DeleteProjectRequest {
    const message = createBaseDeleteProjectRequest();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseDeleteProjectResponse(): DeleteProjectResponse {
  return { project: undefined };
}

export const DeleteProjectResponse: MessageFns<DeleteProjectResponse> = {
  encode(
    message: DeleteProjectResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.project !== undefined) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): DeleteProjectResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteProjectResponse {
    return {
      project: isSet(object.project)
        ? Project.fromJSON(object.project)
        : undefined,
    };
  },

  toJSON(message: DeleteProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteProjectResponse>, I>>(
    base?: I,
  ): DeleteProjectResponse {
    return DeleteProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteProjectResponse>, I>>(
    object: I,
  ): DeleteProjectResponse {
    const message = createBaseDeleteProjectResponse();
    message.project =
      object.project !== undefined && object.project !== null
        ? Project.fromPartial(object.project)
        : undefined;
    return message;
  },
};

function createBaseReadProjectRequest(): ReadProjectRequest {
  return { filter: '' };
}

export const ReadProjectRequest: MessageFns<ReadProjectRequest> = {
  encode(
    message: ReadProjectRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.filter !== '') {
      writer.uint32(10).string(message.filter);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadProjectRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadProjectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadProjectRequest {
    return {
      filter: isSet(object.filter) ? globalThis.String(object.filter) : '',
    };
  },

  toJSON(message: ReadProjectRequest): unknown {
    const obj: any = {};
    if (message.filter !== '') {
      obj.filter = message.filter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadProjectRequest>, I>>(
    base?: I,
  ): ReadProjectRequest {
    return ReadProjectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadProjectRequest>, I>>(
    object: I,
  ): ReadProjectRequest {
    const message = createBaseReadProjectRequest();
    message.filter = object.filter ?? '';
    return message;
  },
};

function createBaseReadProjectResponse(): ReadProjectResponse {
  return { project: undefined };
}

export const ReadProjectResponse: MessageFns<ReadProjectResponse> = {
  encode(
    message: ReadProjectResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.project !== undefined) {
      Project.encode(message.project, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadProjectResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadProjectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.project = Project.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadProjectResponse {
    return {
      project: isSet(object.project)
        ? Project.fromJSON(object.project)
        : undefined,
    };
  },

  toJSON(message: ReadProjectResponse): unknown {
    const obj: any = {};
    if (message.project !== undefined) {
      obj.project = Project.toJSON(message.project);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadProjectResponse>, I>>(
    base?: I,
  ): ReadProjectResponse {
    return ReadProjectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadProjectResponse>, I>>(
    object: I,
  ): ReadProjectResponse {
    const message = createBaseReadProjectResponse();
    message.project =
      object.project !== undefined && object.project !== null
        ? Project.fromPartial(object.project)
        : undefined;
    return message;
  },
};

function createBaseFindProjectsRequest(): FindProjectsRequest {
  return { filter: '', paginate: undefined };
}

export const FindProjectsRequest: MessageFns<FindProjectsRequest> = {
  encode(
    message: FindProjectsRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.filter !== '') {
      writer.uint32(10).string(message.filter);
    }
    if (message.paginate !== undefined) {
      Paginate.encode(message.paginate, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindProjectsRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindProjectsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paginate = Paginate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindProjectsRequest {
    return {
      filter: isSet(object.filter) ? globalThis.String(object.filter) : '',
      paginate: isSet(object.paginate)
        ? Paginate.fromJSON(object.paginate)
        : undefined,
    };
  },

  toJSON(message: FindProjectsRequest): unknown {
    const obj: any = {};
    if (message.filter !== '') {
      obj.filter = message.filter;
    }
    if (message.paginate !== undefined) {
      obj.paginate = Paginate.toJSON(message.paginate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindProjectsRequest>, I>>(
    base?: I,
  ): FindProjectsRequest {
    return FindProjectsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindProjectsRequest>, I>>(
    object: I,
  ): FindProjectsRequest {
    const message = createBaseFindProjectsRequest();
    message.filter = object.filter ?? '';
    message.paginate =
      object.paginate !== undefined && object.paginate !== null
        ? Paginate.fromPartial(object.paginate)
        : undefined;
    return message;
  },
};

function createBaseFindProjectsResponse(): FindProjectsResponse {
  return { projects: [] };
}

export const FindProjectsResponse: MessageFns<FindProjectsResponse> = {
  encode(
    message: FindProjectsResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.projects) {
      Project.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindProjectsResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindProjectsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projects.push(Project.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindProjectsResponse {
    return {
      projects: globalThis.Array.isArray(object?.projects)
        ? object.projects.map((e: any) => Project.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FindProjectsResponse): unknown {
    const obj: any = {};
    if (message.projects?.length) {
      obj.projects = message.projects.map((e) => Project.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindProjectsResponse>, I>>(
    base?: I,
  ): FindProjectsResponse {
    return FindProjectsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindProjectsResponse>, I>>(
    object: I,
  ): FindProjectsResponse {
    const message = createBaseFindProjectsResponse();
    message.projects =
      object.projects?.map((e) => Project.fromPartial(e)) || [];
    return message;
  },
};

export interface ProjectService {
  CreateProject(request: CreateProjectRequest): Promise<CreateProjectResponse>;
  DeleteProject(request: DeleteProjectRequest): Promise<DeleteProjectResponse>;
  UpdateProject(request: UpdateProjectRequest): Promise<UpdateProjectResponse>;
  ReadProject(request: ReadProjectRequest): Promise<ReadProjectResponse>;
  FindProjects(request: FindProjectsRequest): Promise<FindProjectsResponse>;
}

export const ProjectServiceServiceName =
  'io.ultimatebackend.srv.project.ProjectService';
export class ProjectServiceClientImpl implements ProjectService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ProjectServiceServiceName;
    this.rpc = rpc;
    this.CreateProject = this.CreateProject.bind(this);
    this.DeleteProject = this.DeleteProject.bind(this);
    this.UpdateProject = this.UpdateProject.bind(this);
    this.ReadProject = this.ReadProject.bind(this);
    this.FindProjects = this.FindProjects.bind(this);
  }
  CreateProject(request: CreateProjectRequest): Promise<CreateProjectResponse> {
    const data = CreateProjectRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'CreateProject', data);
    return promise.then((data) =>
      CreateProjectResponse.decode(new BinaryReader(data)),
    );
  }

  DeleteProject(request: DeleteProjectRequest): Promise<DeleteProjectResponse> {
    const data = DeleteProjectRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'DeleteProject', data);
    return promise.then((data) =>
      DeleteProjectResponse.decode(new BinaryReader(data)),
    );
  }

  UpdateProject(request: UpdateProjectRequest): Promise<UpdateProjectResponse> {
    const data = UpdateProjectRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'UpdateProject', data);
    return promise.then((data) =>
      UpdateProjectResponse.decode(new BinaryReader(data)),
    );
  }

  ReadProject(request: ReadProjectRequest): Promise<ReadProjectResponse> {
    const data = ReadProjectRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ReadProject', data);
    return promise.then((data) =>
      ReadProjectResponse.decode(new BinaryReader(data)),
    );
  }

  FindProjects(request: FindProjectsRequest): Promise<FindProjectsResponse> {
    const data = FindProjectsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'FindProjects', data);
    return promise.then((data) =>
      FindProjectsResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
