// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/role.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'io.ultimatebackend.srv.role';

export interface StringMessage {
  params: string[];
}

export interface BooleanPayload {
  success: boolean;
}

export interface Role {
  id: string;
  role: string;
  domain: string;
  resource: string;
  action: string;
  name: string;
  normalizedName: string;
  createdAt: string;
  updatedAt: string;
}

export interface UserRole {
  userId: string;
  role: string;
  domain: string;
}

export interface CreateRoleRequest {
  role: string;
  domain: string;
  resource: string;
  action: string;
}

export interface CreateRoleResponse {
  role: Role | undefined;
}

export interface ReadRoleRequest {
  roleId: string;
  domain: string;
}

export interface ReadRoleResponse {
  role: Role | undefined;
}

export interface ReadUserRolesResponse {
  roles: string[];
}

export interface HasRightsRequest {
  sub: string;
  dom: string;
  res: string;
  act: string;
  auth: string;
}

export interface HasRightsResponse {
  access: boolean;
}

export interface ReadUserRolesRequest {
  userId: string;
  tenant: string;
}

export interface FindRolesRequest {
  subId: string;
}

export interface FindRolesResponse {
  roles: Role[];
}

export interface AddUserToRoleRequest {
  role: string;
  userId: string;
  actor: string;
  domain: string;
}

export interface AddUserToRoleResponse {
  roles: string[];
}

export interface AddTenantRolesRequest {
  domain: string;
}

export interface AddTenantRolesResponse {
  success: boolean;
}

export interface RemoveUserFromRoleRequest {
  tenantId: string;
  userId: string;
}

export interface RemoveUserFromRoleResponse {
  success: boolean;
}

export interface AddPolicyRequest {
  params: string[];
}

export interface AddPolicyResponse {
  success: boolean;
}

function createBaseStringMessage(): StringMessage {
  return { params: [] };
}

export const StringMessage: MessageFns<StringMessage> = {
  encode(
    message: StringMessage,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.params) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StringMessage {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStringMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StringMessage {
    return {
      params: globalThis.Array.isArray(object?.params)
        ? object.params.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: StringMessage): unknown {
    const obj: any = {};
    if (message.params?.length) {
      obj.params = message.params;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StringMessage>, I>>(
    base?: I,
  ): StringMessage {
    return StringMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StringMessage>, I>>(
    object: I,
  ): StringMessage {
    const message = createBaseStringMessage();
    message.params = object.params?.map((e) => e) || [];
    return message;
  },
};

function createBaseBooleanPayload(): BooleanPayload {
  return { success: false };
}

export const BooleanPayload: MessageFns<BooleanPayload> = {
  encode(
    message: BooleanPayload,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BooleanPayload {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooleanPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BooleanPayload {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: BooleanPayload): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BooleanPayload>, I>>(
    base?: I,
  ): BooleanPayload {
    return BooleanPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BooleanPayload>, I>>(
    object: I,
  ): BooleanPayload {
    const message = createBaseBooleanPayload();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseRole(): Role {
  return {
    id: '',
    role: '',
    domain: '',
    resource: '',
    action: '',
    name: '',
    normalizedName: '',
    createdAt: '',
    updatedAt: '',
  };
}

export const Role: MessageFns<Role> = {
  encode(
    message: Role,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.role !== '') {
      writer.uint32(18).string(message.role);
    }
    if (message.domain !== '') {
      writer.uint32(26).string(message.domain);
    }
    if (message.resource !== '') {
      writer.uint32(34).string(message.resource);
    }
    if (message.action !== '') {
      writer.uint32(42).string(message.action);
    }
    if (message.name !== '') {
      writer.uint32(50).string(message.name);
    }
    if (message.normalizedName !== '') {
      writer.uint32(58).string(message.normalizedName);
    }
    if (message.createdAt !== '') {
      writer.uint32(66).string(message.createdAt);
    }
    if (message.updatedAt !== '') {
      writer.uint32(74).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Role {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRole();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.normalizedName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Role {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      role: isSet(object.role) ? globalThis.String(object.role) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
      resource: isSet(object.resource)
        ? globalThis.String(object.resource)
        : '',
      action: isSet(object.action) ? globalThis.String(object.action) : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      normalizedName: isSet(object.normalizedName)
        ? globalThis.String(object.normalizedName)
        : '',
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : '',
    };
  },

  toJSON(message: Role): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.role !== '') {
      obj.role = message.role;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    if (message.resource !== '') {
      obj.resource = message.resource;
    }
    if (message.action !== '') {
      obj.action = message.action;
    }
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.normalizedName !== '') {
      obj.normalizedName = message.normalizedName;
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== '') {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Role>, I>>(base?: I): Role {
    return Role.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Role>, I>>(object: I): Role {
    const message = createBaseRole();
    message.id = object.id ?? '';
    message.role = object.role ?? '';
    message.domain = object.domain ?? '';
    message.resource = object.resource ?? '';
    message.action = object.action ?? '';
    message.name = object.name ?? '';
    message.normalizedName = object.normalizedName ?? '';
    message.createdAt = object.createdAt ?? '';
    message.updatedAt = object.updatedAt ?? '';
    return message;
  },
};

function createBaseUserRole(): UserRole {
  return { userId: '', role: '', domain: '' };
}

export const UserRole: MessageFns<UserRole> = {
  encode(
    message: UserRole,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId);
    }
    if (message.role !== '') {
      writer.uint32(18).string(message.role);
    }
    if (message.domain !== '') {
      writer.uint32(26).string(message.domain);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRole {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRole();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRole {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      role: isSet(object.role) ? globalThis.String(object.role) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
    };
  },

  toJSON(message: UserRole): unknown {
    const obj: any = {};
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.role !== '') {
      obj.role = message.role;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRole>, I>>(base?: I): UserRole {
    return UserRole.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRole>, I>>(object: I): UserRole {
    const message = createBaseUserRole();
    message.userId = object.userId ?? '';
    message.role = object.role ?? '';
    message.domain = object.domain ?? '';
    return message;
  },
};

function createBaseCreateRoleRequest(): CreateRoleRequest {
  return { role: '', domain: '', resource: '', action: '' };
}

export const CreateRoleRequest: MessageFns<CreateRoleRequest> = {
  encode(
    message: CreateRoleRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.role !== '') {
      writer.uint32(18).string(message.role);
    }
    if (message.domain !== '') {
      writer.uint32(26).string(message.domain);
    }
    if (message.resource !== '') {
      writer.uint32(34).string(message.resource);
    }
    if (message.action !== '') {
      writer.uint32(42).string(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRoleRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.action = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRoleRequest {
    return {
      role: isSet(object.role) ? globalThis.String(object.role) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
      resource: isSet(object.resource)
        ? globalThis.String(object.resource)
        : '',
      action: isSet(object.action) ? globalThis.String(object.action) : '',
    };
  },

  toJSON(message: CreateRoleRequest): unknown {
    const obj: any = {};
    if (message.role !== '') {
      obj.role = message.role;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    if (message.resource !== '') {
      obj.resource = message.resource;
    }
    if (message.action !== '') {
      obj.action = message.action;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateRoleRequest>, I>>(
    base?: I,
  ): CreateRoleRequest {
    return CreateRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateRoleRequest>, I>>(
    object: I,
  ): CreateRoleRequest {
    const message = createBaseCreateRoleRequest();
    message.role = object.role ?? '';
    message.domain = object.domain ?? '';
    message.resource = object.resource ?? '';
    message.action = object.action ?? '';
    return message;
  },
};

function createBaseCreateRoleResponse(): CreateRoleResponse {
  return { role: undefined };
}

export const CreateRoleResponse: MessageFns<CreateRoleResponse> = {
  encode(
    message: CreateRoleResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.role !== undefined) {
      Role.encode(message.role, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateRoleResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRoleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = Role.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateRoleResponse {
    return {
      role: isSet(object.role) ? Role.fromJSON(object.role) : undefined,
    };
  },

  toJSON(message: CreateRoleResponse): unknown {
    const obj: any = {};
    if (message.role !== undefined) {
      obj.role = Role.toJSON(message.role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateRoleResponse>, I>>(
    base?: I,
  ): CreateRoleResponse {
    return CreateRoleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateRoleResponse>, I>>(
    object: I,
  ): CreateRoleResponse {
    const message = createBaseCreateRoleResponse();
    message.role =
      object.role !== undefined && object.role !== null
        ? Role.fromPartial(object.role)
        : undefined;
    return message;
  },
};

function createBaseReadRoleRequest(): ReadRoleRequest {
  return { roleId: '', domain: '' };
}

export const ReadRoleRequest: MessageFns<ReadRoleRequest> = {
  encode(
    message: ReadRoleRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.roleId !== '') {
      writer.uint32(10).string(message.roleId);
    }
    if (message.domain !== '') {
      writer.uint32(18).string(message.domain);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadRoleRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roleId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadRoleRequest {
    return {
      roleId: isSet(object.roleId) ? globalThis.String(object.roleId) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
    };
  },

  toJSON(message: ReadRoleRequest): unknown {
    const obj: any = {};
    if (message.roleId !== '') {
      obj.roleId = message.roleId;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadRoleRequest>, I>>(
    base?: I,
  ): ReadRoleRequest {
    return ReadRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadRoleRequest>, I>>(
    object: I,
  ): ReadRoleRequest {
    const message = createBaseReadRoleRequest();
    message.roleId = object.roleId ?? '';
    message.domain = object.domain ?? '';
    return message;
  },
};

function createBaseReadRoleResponse(): ReadRoleResponse {
  return { role: undefined };
}

export const ReadRoleResponse: MessageFns<ReadRoleResponse> = {
  encode(
    message: ReadRoleResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.role !== undefined) {
      Role.encode(message.role, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadRoleResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRoleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = Role.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadRoleResponse {
    return {
      role: isSet(object.role) ? Role.fromJSON(object.role) : undefined,
    };
  },

  toJSON(message: ReadRoleResponse): unknown {
    const obj: any = {};
    if (message.role !== undefined) {
      obj.role = Role.toJSON(message.role);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadRoleResponse>, I>>(
    base?: I,
  ): ReadRoleResponse {
    return ReadRoleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadRoleResponse>, I>>(
    object: I,
  ): ReadRoleResponse {
    const message = createBaseReadRoleResponse();
    message.role =
      object.role !== undefined && object.role !== null
        ? Role.fromPartial(object.role)
        : undefined;
    return message;
  },
};

function createBaseReadUserRolesResponse(): ReadUserRolesResponse {
  return { roles: [] };
}

export const ReadUserRolesResponse: MessageFns<ReadUserRolesResponse> = {
  encode(
    message: ReadUserRolesResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.roles) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadUserRolesResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadUserRolesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadUserRolesResponse {
    return {
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ReadUserRolesResponse): unknown {
    const obj: any = {};
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadUserRolesResponse>, I>>(
    base?: I,
  ): ReadUserRolesResponse {
    return ReadUserRolesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadUserRolesResponse>, I>>(
    object: I,
  ): ReadUserRolesResponse {
    const message = createBaseReadUserRolesResponse();
    message.roles = object.roles?.map((e) => e) || [];
    return message;
  },
};

function createBaseHasRightsRequest(): HasRightsRequest {
  return { sub: '', dom: '', res: '', act: '', auth: '' };
}

export const HasRightsRequest: MessageFns<HasRightsRequest> = {
  encode(
    message: HasRightsRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.sub !== '') {
      writer.uint32(10).string(message.sub);
    }
    if (message.dom !== '') {
      writer.uint32(18).string(message.dom);
    }
    if (message.res !== '') {
      writer.uint32(26).string(message.res);
    }
    if (message.act !== '') {
      writer.uint32(34).string(message.act);
    }
    if (message.auth !== '') {
      writer.uint32(42).string(message.auth);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasRightsRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasRightsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sub = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dom = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.res = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.act = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.auth = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasRightsRequest {
    return {
      sub: isSet(object.sub) ? globalThis.String(object.sub) : '',
      dom: isSet(object.dom) ? globalThis.String(object.dom) : '',
      res: isSet(object.res) ? globalThis.String(object.res) : '',
      act: isSet(object.act) ? globalThis.String(object.act) : '',
      auth: isSet(object.auth) ? globalThis.String(object.auth) : '',
    };
  },

  toJSON(message: HasRightsRequest): unknown {
    const obj: any = {};
    if (message.sub !== '') {
      obj.sub = message.sub;
    }
    if (message.dom !== '') {
      obj.dom = message.dom;
    }
    if (message.res !== '') {
      obj.res = message.res;
    }
    if (message.act !== '') {
      obj.act = message.act;
    }
    if (message.auth !== '') {
      obj.auth = message.auth;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasRightsRequest>, I>>(
    base?: I,
  ): HasRightsRequest {
    return HasRightsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasRightsRequest>, I>>(
    object: I,
  ): HasRightsRequest {
    const message = createBaseHasRightsRequest();
    message.sub = object.sub ?? '';
    message.dom = object.dom ?? '';
    message.res = object.res ?? '';
    message.act = object.act ?? '';
    message.auth = object.auth ?? '';
    return message;
  },
};

function createBaseHasRightsResponse(): HasRightsResponse {
  return { access: false };
}

export const HasRightsResponse: MessageFns<HasRightsResponse> = {
  encode(
    message: HasRightsResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.access !== false) {
      writer.uint32(8).bool(message.access);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasRightsResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasRightsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.access = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HasRightsResponse {
    return {
      access: isSet(object.access) ? globalThis.Boolean(object.access) : false,
    };
  },

  toJSON(message: HasRightsResponse): unknown {
    const obj: any = {};
    if (message.access !== false) {
      obj.access = message.access;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HasRightsResponse>, I>>(
    base?: I,
  ): HasRightsResponse {
    return HasRightsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HasRightsResponse>, I>>(
    object: I,
  ): HasRightsResponse {
    const message = createBaseHasRightsResponse();
    message.access = object.access ?? false;
    return message;
  },
};

function createBaseReadUserRolesRequest(): ReadUserRolesRequest {
  return { userId: '', tenant: '' };
}

export const ReadUserRolesRequest: MessageFns<ReadUserRolesRequest> = {
  encode(
    message: ReadUserRolesRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== '') {
      writer.uint32(10).string(message.userId);
    }
    if (message.tenant !== '') {
      writer.uint32(18).string(message.tenant);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadUserRolesRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadUserRolesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenant = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadUserRolesRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : '',
    };
  },

  toJSON(message: ReadUserRolesRequest): unknown {
    const obj: any = {};
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.tenant !== '') {
      obj.tenant = message.tenant;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadUserRolesRequest>, I>>(
    base?: I,
  ): ReadUserRolesRequest {
    return ReadUserRolesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadUserRolesRequest>, I>>(
    object: I,
  ): ReadUserRolesRequest {
    const message = createBaseReadUserRolesRequest();
    message.userId = object.userId ?? '';
    message.tenant = object.tenant ?? '';
    return message;
  },
};

function createBaseFindRolesRequest(): FindRolesRequest {
  return { subId: '' };
}

export const FindRolesRequest: MessageFns<FindRolesRequest> = {
  encode(
    message: FindRolesRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.subId !== '') {
      writer.uint32(10).string(message.subId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindRolesRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindRolesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindRolesRequest {
    return {
      subId: isSet(object.subId) ? globalThis.String(object.subId) : '',
    };
  },

  toJSON(message: FindRolesRequest): unknown {
    const obj: any = {};
    if (message.subId !== '') {
      obj.subId = message.subId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindRolesRequest>, I>>(
    base?: I,
  ): FindRolesRequest {
    return FindRolesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindRolesRequest>, I>>(
    object: I,
  ): FindRolesRequest {
    const message = createBaseFindRolesRequest();
    message.subId = object.subId ?? '';
    return message;
  },
};

function createBaseFindRolesResponse(): FindRolesResponse {
  return { roles: [] };
}

export const FindRolesResponse: MessageFns<FindRolesResponse> = {
  encode(
    message: FindRolesResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.roles) {
      Role.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindRolesResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindRolesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roles.push(Role.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindRolesResponse {
    return {
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => Role.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FindRolesResponse): unknown {
    const obj: any = {};
    if (message.roles?.length) {
      obj.roles = message.roles.map((e) => Role.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindRolesResponse>, I>>(
    base?: I,
  ): FindRolesResponse {
    return FindRolesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindRolesResponse>, I>>(
    object: I,
  ): FindRolesResponse {
    const message = createBaseFindRolesResponse();
    message.roles = object.roles?.map((e) => Role.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddUserToRoleRequest(): AddUserToRoleRequest {
  return { role: '', userId: '', actor: '', domain: '' };
}

export const AddUserToRoleRequest: MessageFns<AddUserToRoleRequest> = {
  encode(
    message: AddUserToRoleRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.role !== '') {
      writer.uint32(10).string(message.role);
    }
    if (message.userId !== '') {
      writer.uint32(18).string(message.userId);
    }
    if (message.actor !== '') {
      writer.uint32(26).string(message.actor);
    }
    if (message.domain !== '') {
      writer.uint32(34).string(message.domain);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): AddUserToRoleRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddUserToRoleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actor = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddUserToRoleRequest {
    return {
      role: isSet(object.role) ? globalThis.String(object.role) : '',
      userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      actor: isSet(object.actor) ? globalThis.String(object.actor) : '',
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
    };
  },

  toJSON(message: AddUserToRoleRequest): unknown {
    const obj: any = {};
    if (message.role !== '') {
      obj.role = message.role;
    }
    if (message.userId !== '') {
      obj.userId = message.userId;
    }
    if (message.actor !== '') {
      obj.actor = message.actor;
    }
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddUserToRoleRequest>, I>>(
    base?: I,
  ): AddUserToRoleRequest {
    return AddUserToRoleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddUserToRoleRequest>, I>>(
    object: I,
  ): AddUserToRoleRequest {
    const message = createBaseAddUserToRoleRequest();
    message.role = object.role ?? '';
    message.userId = object.userId ?? '';
    message.actor = object.actor ?? '';
    message.domain = object.domain ?? '';
    return message;
  },
};

function createBaseAddUserToRoleResponse(): AddUserToRoleResponse {
  return { roles: [] };
}

export const AddUserToRoleResponse: MessageFns<AddUserToRoleResponse> = {
  encode(
    message: AddUserToRoleResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.roles) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): AddUserToRoleResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddUserToRoleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddUserToRoleResponse {
    return {
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: AddUserToRoleResponse): unknown {
    const obj: any = {};
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddUserToRoleResponse>, I>>(
    base?: I,
  ): AddUserToRoleResponse {
    return AddUserToRoleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddUserToRoleResponse>, I>>(
    object: I,
  ): AddUserToRoleResponse {
    const message = createBaseAddUserToRoleResponse();
    message.roles = object.roles?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddTenantRolesRequest(): AddTenantRolesRequest {
  return { domain: '' };
}

export const AddTenantRolesRequest: MessageFns<AddTenantRolesRequest> = {
  encode(
    message: AddTenantRolesRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.domain !== '') {
      writer.uint32(10).string(message.domain);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): AddTenantRolesRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddTenantRolesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddTenantRolesRequest {
    return {
      domain: isSet(object.domain) ? globalThis.String(object.domain) : '',
    };
  },

  toJSON(message: AddTenantRolesRequest): unknown {
    const obj: any = {};
    if (message.domain !== '') {
      obj.domain = message.domain;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddTenantRolesRequest>, I>>(
    base?: I,
  ): AddTenantRolesRequest {
    return AddTenantRolesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddTenantRolesRequest>, I>>(
    object: I,
  ): AddTenantRolesRequest {
    const message = createBaseAddTenantRolesRequest();
    message.domain = object.domain ?? '';
    return message;
  },
};

function createBaseAddTenantRolesResponse(): AddTenantRolesResponse {
  return { success: false };
}

export const AddTenantRolesResponse: MessageFns<AddTenantRolesResponse> = {
  encode(
    message: AddTenantRolesResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): AddTenantRolesResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddTenantRolesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddTenantRolesResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: AddTenantRolesResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddTenantRolesResponse>, I>>(
    base?: I,
  ): AddTenantRolesResponse {
    return AddTenantRolesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddTenantRolesResponse>, I>>(
    object: I,
  ): AddTenantRolesResponse {
    const message = createBaseAddTenantRolesResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseRemoveUserFromRoleRequest(): RemoveUserFromRoleRequest {
  return { tenantId: '', userId: '' };
}

export const RemoveUserFromRoleRequest: MessageFns<RemoveUserFromRoleRequest> =
  {
    encode(
      message: RemoveUserFromRoleRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.tenantId !== '') {
        writer.uint32(10).string(message.tenantId);
      }
      if (message.userId !== '') {
        writer.uint32(18).string(message.userId);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): RemoveUserFromRoleRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRemoveUserFromRoleRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.tenantId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.userId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): RemoveUserFromRoleRequest {
      return {
        tenantId: isSet(object.tenantId)
          ? globalThis.String(object.tenantId)
          : '',
        userId: isSet(object.userId) ? globalThis.String(object.userId) : '',
      };
    },

    toJSON(message: RemoveUserFromRoleRequest): unknown {
      const obj: any = {};
      if (message.tenantId !== '') {
        obj.tenantId = message.tenantId;
      }
      if (message.userId !== '') {
        obj.userId = message.userId;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<RemoveUserFromRoleRequest>, I>>(
      base?: I,
    ): RemoveUserFromRoleRequest {
      return RemoveUserFromRoleRequest.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<RemoveUserFromRoleRequest>, I>>(
      object: I,
    ): RemoveUserFromRoleRequest {
      const message = createBaseRemoveUserFromRoleRequest();
      message.tenantId = object.tenantId ?? '';
      message.userId = object.userId ?? '';
      return message;
    },
  };

function createBaseRemoveUserFromRoleResponse(): RemoveUserFromRoleResponse {
  return { success: false };
}

export const RemoveUserFromRoleResponse: MessageFns<RemoveUserFromRoleResponse> =
  {
    encode(
      message: RemoveUserFromRoleResponse,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.success !== false) {
        writer.uint32(8).bool(message.success);
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): RemoveUserFromRoleResponse {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRemoveUserFromRoleResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.success = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): RemoveUserFromRoleResponse {
      return {
        success: isSet(object.success)
          ? globalThis.Boolean(object.success)
          : false,
      };
    },

    toJSON(message: RemoveUserFromRoleResponse): unknown {
      const obj: any = {};
      if (message.success !== false) {
        obj.success = message.success;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<RemoveUserFromRoleResponse>, I>>(
      base?: I,
    ): RemoveUserFromRoleResponse {
      return RemoveUserFromRoleResponse.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<RemoveUserFromRoleResponse>, I>>(
      object: I,
    ): RemoveUserFromRoleResponse {
      const message = createBaseRemoveUserFromRoleResponse();
      message.success = object.success ?? false;
      return message;
    },
  };

function createBaseAddPolicyRequest(): AddPolicyRequest {
  return { params: [] };
}

export const AddPolicyRequest: MessageFns<AddPolicyRequest> = {
  encode(
    message: AddPolicyRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.params) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPolicyRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPolicyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddPolicyRequest {
    return {
      params: globalThis.Array.isArray(object?.params)
        ? object.params.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: AddPolicyRequest): unknown {
    const obj: any = {};
    if (message.params?.length) {
      obj.params = message.params;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddPolicyRequest>, I>>(
    base?: I,
  ): AddPolicyRequest {
    return AddPolicyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddPolicyRequest>, I>>(
    object: I,
  ): AddPolicyRequest {
    const message = createBaseAddPolicyRequest();
    message.params = object.params?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddPolicyResponse(): AddPolicyResponse {
  return { success: false };
}

export const AddPolicyResponse: MessageFns<AddPolicyResponse> = {
  encode(
    message: AddPolicyResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPolicyResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPolicyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddPolicyResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: AddPolicyResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddPolicyResponse>, I>>(
    base?: I,
  ): AddPolicyResponse {
    return AddPolicyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddPolicyResponse>, I>>(
    object: I,
  ): AddPolicyResponse {
    const message = createBaseAddPolicyResponse();
    message.success = object.success ?? false;
    return message;
  },
};

export interface RoleService {
  CreateRole(request: CreateRoleRequest): Promise<CreateRoleResponse>;
  ReadRole(request: ReadRoleRequest): Promise<ReadRoleResponse>;
  HasRights(request: HasRightsRequest): Promise<HasRightsResponse>;
  AddPolicy(request: AddPolicyRequest): Promise<AddPolicyResponse>;
  AddTenantRoles(
    request: AddTenantRolesRequest,
  ): Promise<AddTenantRolesResponse>;
  AddUserToRole(request: AddUserToRoleRequest): Promise<AddUserToRoleResponse>;
  RemoveUserFromRole(
    request: RemoveUserFromRoleRequest,
  ): Promise<RemoveUserFromRoleResponse>;
  ReadUserRoles(request: ReadUserRolesRequest): Promise<ReadUserRolesResponse>;
}

export const RoleServiceServiceName = 'io.ultimatebackend.srv.role.RoleService';
export class RoleServiceClientImpl implements RoleService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || RoleServiceServiceName;
    this.rpc = rpc;
    this.CreateRole = this.CreateRole.bind(this);
    this.ReadRole = this.ReadRole.bind(this);
    this.HasRights = this.HasRights.bind(this);
    this.AddPolicy = this.AddPolicy.bind(this);
    this.AddTenantRoles = this.AddTenantRoles.bind(this);
    this.AddUserToRole = this.AddUserToRole.bind(this);
    this.RemoveUserFromRole = this.RemoveUserFromRole.bind(this);
    this.ReadUserRoles = this.ReadUserRoles.bind(this);
  }
  CreateRole(request: CreateRoleRequest): Promise<CreateRoleResponse> {
    const data = CreateRoleRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'CreateRole', data);
    return promise.then((data) =>
      CreateRoleResponse.decode(new BinaryReader(data)),
    );
  }

  ReadRole(request: ReadRoleRequest): Promise<ReadRoleResponse> {
    const data = ReadRoleRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ReadRole', data);
    return promise.then((data) =>
      ReadRoleResponse.decode(new BinaryReader(data)),
    );
  }

  HasRights(request: HasRightsRequest): Promise<HasRightsResponse> {
    const data = HasRightsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'HasRights', data);
    return promise.then((data) =>
      HasRightsResponse.decode(new BinaryReader(data)),
    );
  }

  AddPolicy(request: AddPolicyRequest): Promise<AddPolicyResponse> {
    const data = AddPolicyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'AddPolicy', data);
    return promise.then((data) =>
      AddPolicyResponse.decode(new BinaryReader(data)),
    );
  }

  AddTenantRoles(
    request: AddTenantRolesRequest,
  ): Promise<AddTenantRolesResponse> {
    const data = AddTenantRolesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'AddTenantRoles', data);
    return promise.then((data) =>
      AddTenantRolesResponse.decode(new BinaryReader(data)),
    );
  }

  AddUserToRole(request: AddUserToRoleRequest): Promise<AddUserToRoleResponse> {
    const data = AddUserToRoleRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'AddUserToRole', data);
    return promise.then((data) =>
      AddUserToRoleResponse.decode(new BinaryReader(data)),
    );
  }

  RemoveUserFromRole(
    request: RemoveUserFromRoleRequest,
  ): Promise<RemoveUserFromRoleResponse> {
    const data = RemoveUserFromRoleRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'RemoveUserFromRole', data);
    return promise.then((data) =>
      RemoveUserFromRoleResponse.decode(new BinaryReader(data)),
    );
  }

  ReadUserRoles(request: ReadUserRolesRequest): Promise<ReadUserRolesResponse> {
    const data = ReadUserRolesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ReadUserRoles', data);
    return promise.then((data) =>
      ReadUserRolesResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
