// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/tenant.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "io.ultimatebackend.srv.tenant";

export enum InvitationStatus {
  /** PENDING - option allow_alias = true; */
  PENDING = 0,
  ACCEPTED = 1,
  REJECTED = 2,
  UNRECOGNIZED = -1,
}

export function invitationStatusFromJSON(object: any): InvitationStatus {
  switch (object) {
    case 0:
    case "PENDING":
      return InvitationStatus.PENDING;
    case 1:
    case "ACCEPTED":
      return InvitationStatus.ACCEPTED;
    case 2:
    case "REJECTED":
      return InvitationStatus.REJECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InvitationStatus.UNRECOGNIZED;
  }
}

export function invitationStatusToJSON(object: InvitationStatus): string {
  switch (object) {
    case InvitationStatus.PENDING:
      return "PENDING";
    case InvitationStatus.ACCEPTED:
      return "ACCEPTED";
    case InvitationStatus.REJECTED:
      return "REJECTED";
    case InvitationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Tenant {
  /** @inject_tag: bson:"_id,omitempty" */
  id: string;
  /** @inject_tag: bson:"normalizedName,omitempty" */
  normalizedName: string;
  /** @inject_tag: bson:"name,omitempty" */
  name: string;
  /** @inject_tag: bson:"tokens,omitempty" */
  tokens: TenantAccess[];
  /** @inject_tag: bson:"createdBy,omitempty" */
  createdBy: string;
  /** @inject_tag: bson:"createdAt,omitempty" */
  createdAt: string;
  /** @inject_tag: bson:"updatedAt,omitempty" */
  updatedAt: string;
  /** @inject_tag: bson:"members,omitempty" */
  members: Member[];
  /** @inject_tag: bson:"settings,omitempty" */
  settings:
    | Settings
    | undefined;
  /** @inject_tag: bson:"payment,omitempty" */
  billing:
    | BillingSettings
    | undefined;
  /** @inject_tag: bson:"payment,omitempty" */
  totalPoints: number;
}

export interface UpdateTenantPayload {
  /** @inject_tag: bson:"name,omitempty" */
  name: string;
  /** @inject_tag: bson:"settings,omitempty" */
  settings: Settings | undefined;
}

export interface TenantAccess {
  /** @inject_tag: bson:"key,omitempty" */
  key: string;
  /** @inject_tag: bson:"secret,omitempty" */
  secret: string;
  /** @inject_tag: bson:"active,omitempty" */
  active: boolean;
  /** @inject_tag: bson:"createdAt,omitempty" */
  createdAt: string;
}

export interface BillingSettings {
  /** @inject_tag: bson:"currentPlan,omitempty" */
  currentPlan: string;
  /** @inject_tag: bson:"subscriptionPlan,omitempty" */
  currentSubscription: string;
}

export interface ConnectionSettings {
  /** @inject_tag: bson:"host,omitempty" */
  host: string;
}

export interface IotSubSettings {
  /** @inject_tag: bson:"uri,omitempty" */
  uri: string;
  /** @inject_tag: bson:"port,omitempty" */
  port: string;
  /** @inject_tag: bson:"password,omitempty" */
  password: string;
  /** @inject_tag: bson:"username,omitempty" */
  username: string;
}

export interface Settings {
  /** @inject_tag: bson:"connection,omitempty" */
  showStatusIcon: boolean;
  /** @inject_tag: bson:"connection,omitempty" */
  connection:
    | ConnectionSettings
    | undefined;
  /** @inject_tag: bson:"mqtt,omitempty" */
  mqtt: IotSubSettings | undefined;
}

export interface Member {
  /** @inject_tag: bson:"id,omitempty" */
  id: string;
  /** @inject_tag: bson:"email,omitempty" */
  email: string;
  /** @inject_tag: bson:"userId,omitempty" */
  userId: string;
  /** @inject_tag: bson:"createdAt,omitempty" */
  createdAt: string;
  /** @inject_tag: bson:"status,omitempty" */
  status: string;
  /** @inject_tag: bson:"role,omitempty" */
  role: string;
  /** @inject_tag: bson:"updatedAt,omitempty" */
  updatedAt: string;
}

/** Tenant */
export interface CreateTenantRequest {
  name: string;
  planId: string;
  couponId: string;
  cardId: string;
}

export interface CreateTenantResponse {
  tenant: Tenant | undefined;
}

export interface FindTenantRequest {
  filter: string;
}

export interface TenantAvailableRequest {
  identifier: string;
}

export interface TenantAvailableResponse {
  available: boolean;
}

export interface FindTenantResponse {
  tenants: Tenant[];
}

export interface DeleteTenantRequest {
  id: string;
}

export interface DeleteTenantResponse {
  tenant: Tenant | undefined;
}

export interface ReadTenantRequest {
  filter: string;
}

export interface ReadTenantResponse {
  tenant: Tenant | undefined;
}

export interface UpdateTenantRequest {
  /** @inject_tag: bson:"_id,omitempty" */
  id: string;
  data: UpdateTenantPayload | undefined;
}

export interface UpdateTenantResponse {
  tenant: Tenant | undefined;
}

/** Tenant Members */
export interface InviteMemberRequest {
  /** @inject_tag: bson:"email,omitempty" */
  email: string;
  /** @inject_tag: bson:"userId,omitempty" */
  userId: string;
  /** @inject_tag: bson:"role,omitempty" */
  role: string;
}

export interface InviteMemberResponse {
  member: Member | undefined;
}

export interface FindMemberRequest {
  status: string;
  role: string;
  tenantId: string;
}

export interface FindMemberResponse {
  members: Member[];
}

export interface DeleteMemberRequest {
  id: string;
}

export interface DeleteMemberResponse {
  member: Member | undefined;
}

export interface ReadMemberRequest {
  /** @inject_tag: bson:"id,omitempty" */
  id: string;
}

export interface ReadMemberResponse {
  member: Member | undefined;
}

export interface UpdateMemberRequest {
  /** @inject_tag: bson:"id,omitempty" */
  id: string;
  /** @inject_tag: bson:"status,omitempty" */
  status: string;
  /** @inject_tag: bson:"role,omitempty" */
  role: string;
}

export interface UpdateMemberResponse {
  member: Member | undefined;
}

export interface AcceptMemberInvitationRequest {
  /** @inject_tag: bson:"token,omitempty" */
  token: string;
}

export interface AcceptMemberInvitationResponse {
  member: Member | undefined;
}

function createBaseTenant(): Tenant {
  return {
    id: "",
    normalizedName: "",
    name: "",
    tokens: [],
    createdBy: "",
    createdAt: "",
    updatedAt: "",
    members: [],
    settings: undefined,
    billing: undefined,
    totalPoints: 0,
  };
}

export const Tenant: MessageFns<Tenant> = {
  encode(message: Tenant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.normalizedName !== "") {
      writer.uint32(18).string(message.normalizedName);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    for (const v of message.tokens) {
      TenantAccess.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.createdBy !== "") {
      writer.uint32(42).string(message.createdBy);
    }
    if (message.createdAt !== "") {
      writer.uint32(50).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(58).string(message.updatedAt);
    }
    for (const v of message.members) {
      Member.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.settings !== undefined) {
      Settings.encode(message.settings, writer.uint32(74).fork()).join();
    }
    if (message.billing !== undefined) {
      BillingSettings.encode(message.billing, writer.uint32(82).fork()).join();
    }
    if (message.totalPoints !== 0) {
      writer.uint32(88).int32(message.totalPoints);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tenant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTenant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.normalizedName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tokens.push(TenantAccess.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.members.push(Member.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.settings = Settings.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.billing = BillingSettings.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.totalPoints = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tenant {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      normalizedName: isSet(object.normalizedName) ? globalThis.String(object.normalizedName) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      tokens: globalThis.Array.isArray(object?.tokens) ? object.tokens.map((e: any) => TenantAccess.fromJSON(e)) : [],
      createdBy: isSet(object.createdBy) ? globalThis.String(object.createdBy) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
      members: globalThis.Array.isArray(object?.members) ? object.members.map((e: any) => Member.fromJSON(e)) : [],
      settings: isSet(object.settings) ? Settings.fromJSON(object.settings) : undefined,
      billing: isSet(object.billing) ? BillingSettings.fromJSON(object.billing) : undefined,
      totalPoints: isSet(object.totalPoints) ? globalThis.Number(object.totalPoints) : 0,
    };
  },

  toJSON(message: Tenant): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.normalizedName !== "") {
      obj.normalizedName = message.normalizedName;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.tokens?.length) {
      obj.tokens = message.tokens.map((e) => TenantAccess.toJSON(e));
    }
    if (message.createdBy !== "") {
      obj.createdBy = message.createdBy;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    if (message.members?.length) {
      obj.members = message.members.map((e) => Member.toJSON(e));
    }
    if (message.settings !== undefined) {
      obj.settings = Settings.toJSON(message.settings);
    }
    if (message.billing !== undefined) {
      obj.billing = BillingSettings.toJSON(message.billing);
    }
    if (message.totalPoints !== 0) {
      obj.totalPoints = Math.round(message.totalPoints);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Tenant>, I>>(base?: I): Tenant {
    return Tenant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tenant>, I>>(object: I): Tenant {
    const message = createBaseTenant();
    message.id = object.id ?? "";
    message.normalizedName = object.normalizedName ?? "";
    message.name = object.name ?? "";
    message.tokens = object.tokens?.map((e) => TenantAccess.fromPartial(e)) || [];
    message.createdBy = object.createdBy ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    message.members = object.members?.map((e) => Member.fromPartial(e)) || [];
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? Settings.fromPartial(object.settings)
      : undefined;
    message.billing = (object.billing !== undefined && object.billing !== null)
      ? BillingSettings.fromPartial(object.billing)
      : undefined;
    message.totalPoints = object.totalPoints ?? 0;
    return message;
  },
};

function createBaseUpdateTenantPayload(): UpdateTenantPayload {
  return { name: "", settings: undefined };
}

export const UpdateTenantPayload: MessageFns<UpdateTenantPayload> = {
  encode(message: UpdateTenantPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.settings !== undefined) {
      Settings.encode(message.settings, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTenantPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTenantPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.settings = Settings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTenantPayload {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      settings: isSet(object.settings) ? Settings.fromJSON(object.settings) : undefined,
    };
  },

  toJSON(message: UpdateTenantPayload): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.settings !== undefined) {
      obj.settings = Settings.toJSON(message.settings);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTenantPayload>, I>>(base?: I): UpdateTenantPayload {
    return UpdateTenantPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTenantPayload>, I>>(object: I): UpdateTenantPayload {
    const message = createBaseUpdateTenantPayload();
    message.name = object.name ?? "";
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? Settings.fromPartial(object.settings)
      : undefined;
    return message;
  },
};

function createBaseTenantAccess(): TenantAccess {
  return { key: "", secret: "", active: false, createdAt: "" };
}

export const TenantAccess: MessageFns<TenantAccess> = {
  encode(message: TenantAccess, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.secret !== "") {
      writer.uint32(18).string(message.secret);
    }
    if (message.active !== false) {
      writer.uint32(24).bool(message.active);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TenantAccess {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTenantAccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.secret = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TenantAccess {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      secret: isSet(object.secret) ? globalThis.String(object.secret) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: TenantAccess): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.secret !== "") {
      obj.secret = message.secret;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TenantAccess>, I>>(base?: I): TenantAccess {
    return TenantAccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TenantAccess>, I>>(object: I): TenantAccess {
    const message = createBaseTenantAccess();
    message.key = object.key ?? "";
    message.secret = object.secret ?? "";
    message.active = object.active ?? false;
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseBillingSettings(): BillingSettings {
  return { currentPlan: "", currentSubscription: "" };
}

export const BillingSettings: MessageFns<BillingSettings> = {
  encode(message: BillingSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentPlan !== "") {
      writer.uint32(10).string(message.currentPlan);
    }
    if (message.currentSubscription !== "") {
      writer.uint32(18).string(message.currentSubscription);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BillingSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBillingSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.currentPlan = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currentSubscription = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BillingSettings {
    return {
      currentPlan: isSet(object.currentPlan) ? globalThis.String(object.currentPlan) : "",
      currentSubscription: isSet(object.currentSubscription) ? globalThis.String(object.currentSubscription) : "",
    };
  },

  toJSON(message: BillingSettings): unknown {
    const obj: any = {};
    if (message.currentPlan !== "") {
      obj.currentPlan = message.currentPlan;
    }
    if (message.currentSubscription !== "") {
      obj.currentSubscription = message.currentSubscription;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BillingSettings>, I>>(base?: I): BillingSettings {
    return BillingSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BillingSettings>, I>>(object: I): BillingSettings {
    const message = createBaseBillingSettings();
    message.currentPlan = object.currentPlan ?? "";
    message.currentSubscription = object.currentSubscription ?? "";
    return message;
  },
};

function createBaseConnectionSettings(): ConnectionSettings {
  return { host: "" };
}

export const ConnectionSettings: MessageFns<ConnectionSettings> = {
  encode(message: ConnectionSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.host !== "") {
      writer.uint32(10).string(message.host);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectionSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectionSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.host = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectionSettings {
    return { host: isSet(object.host) ? globalThis.String(object.host) : "" };
  },

  toJSON(message: ConnectionSettings): unknown {
    const obj: any = {};
    if (message.host !== "") {
      obj.host = message.host;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectionSettings>, I>>(base?: I): ConnectionSettings {
    return ConnectionSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectionSettings>, I>>(object: I): ConnectionSettings {
    const message = createBaseConnectionSettings();
    message.host = object.host ?? "";
    return message;
  },
};

function createBaseIotSubSettings(): IotSubSettings {
  return { uri: "", port: "", password: "", username: "" };
}

export const IotSubSettings: MessageFns<IotSubSettings> = {
  encode(message: IotSubSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uri !== "") {
      writer.uint32(10).string(message.uri);
    }
    if (message.port !== "") {
      writer.uint32(18).string(message.port);
    }
    if (message.password !== "") {
      writer.uint32(26).string(message.password);
    }
    if (message.username !== "") {
      writer.uint32(34).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IotSubSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIotSubSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uri = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.port = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IotSubSettings {
    return {
      uri: isSet(object.uri) ? globalThis.String(object.uri) : "",
      port: isSet(object.port) ? globalThis.String(object.port) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: IotSubSettings): unknown {
    const obj: any = {};
    if (message.uri !== "") {
      obj.uri = message.uri;
    }
    if (message.port !== "") {
      obj.port = message.port;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IotSubSettings>, I>>(base?: I): IotSubSettings {
    return IotSubSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IotSubSettings>, I>>(object: I): IotSubSettings {
    const message = createBaseIotSubSettings();
    message.uri = object.uri ?? "";
    message.port = object.port ?? "";
    message.password = object.password ?? "";
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseSettings(): Settings {
  return { showStatusIcon: false, connection: undefined, mqtt: undefined };
}

export const Settings: MessageFns<Settings> = {
  encode(message: Settings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.showStatusIcon !== false) {
      writer.uint32(8).bool(message.showStatusIcon);
    }
    if (message.connection !== undefined) {
      ConnectionSettings.encode(message.connection, writer.uint32(18).fork()).join();
    }
    if (message.mqtt !== undefined) {
      IotSubSettings.encode(message.mqtt, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Settings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.showStatusIcon = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.connection = ConnectionSettings.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mqtt = IotSubSettings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Settings {
    return {
      showStatusIcon: isSet(object.showStatusIcon) ? globalThis.Boolean(object.showStatusIcon) : false,
      connection: isSet(object.connection) ? ConnectionSettings.fromJSON(object.connection) : undefined,
      mqtt: isSet(object.mqtt) ? IotSubSettings.fromJSON(object.mqtt) : undefined,
    };
  },

  toJSON(message: Settings): unknown {
    const obj: any = {};
    if (message.showStatusIcon !== false) {
      obj.showStatusIcon = message.showStatusIcon;
    }
    if (message.connection !== undefined) {
      obj.connection = ConnectionSettings.toJSON(message.connection);
    }
    if (message.mqtt !== undefined) {
      obj.mqtt = IotSubSettings.toJSON(message.mqtt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Settings>, I>>(base?: I): Settings {
    return Settings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Settings>, I>>(object: I): Settings {
    const message = createBaseSettings();
    message.showStatusIcon = object.showStatusIcon ?? false;
    message.connection = (object.connection !== undefined && object.connection !== null)
      ? ConnectionSettings.fromPartial(object.connection)
      : undefined;
    message.mqtt = (object.mqtt !== undefined && object.mqtt !== null)
      ? IotSubSettings.fromPartial(object.mqtt)
      : undefined;
    return message;
  },
};

function createBaseMember(): Member {
  return { id: "", email: "", userId: "", createdAt: "", status: "", role: "", updatedAt: "" };
}

export const Member: MessageFns<Member> = {
  encode(message: Member, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.role !== "") {
      writer.uint32(50).string(message.role);
    }
    if (message.updatedAt !== "") {
      writer.uint32(58).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Member {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Member {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: Member): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Member>, I>>(base?: I): Member {
    return Member.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Member>, I>>(object: I): Member {
    const message = createBaseMember();
    message.id = object.id ?? "";
    message.email = object.email ?? "";
    message.userId = object.userId ?? "";
    message.createdAt = object.createdAt ?? "";
    message.status = object.status ?? "";
    message.role = object.role ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseCreateTenantRequest(): CreateTenantRequest {
  return { name: "", planId: "", couponId: "", cardId: "" };
}

export const CreateTenantRequest: MessageFns<CreateTenantRequest> = {
  encode(message: CreateTenantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.planId !== "") {
      writer.uint32(18).string(message.planId);
    }
    if (message.couponId !== "") {
      writer.uint32(26).string(message.couponId);
    }
    if (message.cardId !== "") {
      writer.uint32(34).string(message.cardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTenantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTenantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.couponId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTenantRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      planId: isSet(object.planId) ? globalThis.String(object.planId) : "",
      couponId: isSet(object.couponId) ? globalThis.String(object.couponId) : "",
      cardId: isSet(object.cardId) ? globalThis.String(object.cardId) : "",
    };
  },

  toJSON(message: CreateTenantRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.planId !== "") {
      obj.planId = message.planId;
    }
    if (message.couponId !== "") {
      obj.couponId = message.couponId;
    }
    if (message.cardId !== "") {
      obj.cardId = message.cardId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTenantRequest>, I>>(base?: I): CreateTenantRequest {
    return CreateTenantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTenantRequest>, I>>(object: I): CreateTenantRequest {
    const message = createBaseCreateTenantRequest();
    message.name = object.name ?? "";
    message.planId = object.planId ?? "";
    message.couponId = object.couponId ?? "";
    message.cardId = object.cardId ?? "";
    return message;
  },
};

function createBaseCreateTenantResponse(): CreateTenantResponse {
  return { tenant: undefined };
}

export const CreateTenantResponse: MessageFns<CreateTenantResponse> = {
  encode(message: CreateTenantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenant !== undefined) {
      Tenant.encode(message.tenant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTenantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTenantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenant = Tenant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTenantResponse {
    return { tenant: isSet(object.tenant) ? Tenant.fromJSON(object.tenant) : undefined };
  },

  toJSON(message: CreateTenantResponse): unknown {
    const obj: any = {};
    if (message.tenant !== undefined) {
      obj.tenant = Tenant.toJSON(message.tenant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTenantResponse>, I>>(base?: I): CreateTenantResponse {
    return CreateTenantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTenantResponse>, I>>(object: I): CreateTenantResponse {
    const message = createBaseCreateTenantResponse();
    message.tenant = (object.tenant !== undefined && object.tenant !== null)
      ? Tenant.fromPartial(object.tenant)
      : undefined;
    return message;
  },
};

function createBaseFindTenantRequest(): FindTenantRequest {
  return { filter: "" };
}

export const FindTenantRequest: MessageFns<FindTenantRequest> = {
  encode(message: FindTenantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== "") {
      writer.uint32(10).string(message.filter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindTenantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindTenantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindTenantRequest {
    return { filter: isSet(object.filter) ? globalThis.String(object.filter) : "" };
  },

  toJSON(message: FindTenantRequest): unknown {
    const obj: any = {};
    if (message.filter !== "") {
      obj.filter = message.filter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindTenantRequest>, I>>(base?: I): FindTenantRequest {
    return FindTenantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindTenantRequest>, I>>(object: I): FindTenantRequest {
    const message = createBaseFindTenantRequest();
    message.filter = object.filter ?? "";
    return message;
  },
};

function createBaseTenantAvailableRequest(): TenantAvailableRequest {
  return { identifier: "" };
}

export const TenantAvailableRequest: MessageFns<TenantAvailableRequest> = {
  encode(message: TenantAvailableRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TenantAvailableRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTenantAvailableRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TenantAvailableRequest {
    return { identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "" };
  },

  toJSON(message: TenantAvailableRequest): unknown {
    const obj: any = {};
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TenantAvailableRequest>, I>>(base?: I): TenantAvailableRequest {
    return TenantAvailableRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TenantAvailableRequest>, I>>(object: I): TenantAvailableRequest {
    const message = createBaseTenantAvailableRequest();
    message.identifier = object.identifier ?? "";
    return message;
  },
};

function createBaseTenantAvailableResponse(): TenantAvailableResponse {
  return { available: false };
}

export const TenantAvailableResponse: MessageFns<TenantAvailableResponse> = {
  encode(message: TenantAvailableResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.available !== false) {
      writer.uint32(8).bool(message.available);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TenantAvailableResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTenantAvailableResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.available = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TenantAvailableResponse {
    return { available: isSet(object.available) ? globalThis.Boolean(object.available) : false };
  },

  toJSON(message: TenantAvailableResponse): unknown {
    const obj: any = {};
    if (message.available !== false) {
      obj.available = message.available;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TenantAvailableResponse>, I>>(base?: I): TenantAvailableResponse {
    return TenantAvailableResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TenantAvailableResponse>, I>>(object: I): TenantAvailableResponse {
    const message = createBaseTenantAvailableResponse();
    message.available = object.available ?? false;
    return message;
  },
};

function createBaseFindTenantResponse(): FindTenantResponse {
  return { tenants: [] };
}

export const FindTenantResponse: MessageFns<FindTenantResponse> = {
  encode(message: FindTenantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tenants) {
      Tenant.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindTenantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindTenantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenants.push(Tenant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindTenantResponse {
    return {
      tenants: globalThis.Array.isArray(object?.tenants) ? object.tenants.map((e: any) => Tenant.fromJSON(e)) : [],
    };
  },

  toJSON(message: FindTenantResponse): unknown {
    const obj: any = {};
    if (message.tenants?.length) {
      obj.tenants = message.tenants.map((e) => Tenant.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindTenantResponse>, I>>(base?: I): FindTenantResponse {
    return FindTenantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindTenantResponse>, I>>(object: I): FindTenantResponse {
    const message = createBaseFindTenantResponse();
    message.tenants = object.tenants?.map((e) => Tenant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteTenantRequest(): DeleteTenantRequest {
  return { id: "" };
}

export const DeleteTenantRequest: MessageFns<DeleteTenantRequest> = {
  encode(message: DeleteTenantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTenantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTenantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTenantRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteTenantRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTenantRequest>, I>>(base?: I): DeleteTenantRequest {
    return DeleteTenantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTenantRequest>, I>>(object: I): DeleteTenantRequest {
    const message = createBaseDeleteTenantRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteTenantResponse(): DeleteTenantResponse {
  return { tenant: undefined };
}

export const DeleteTenantResponse: MessageFns<DeleteTenantResponse> = {
  encode(message: DeleteTenantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenant !== undefined) {
      Tenant.encode(message.tenant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTenantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTenantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenant = Tenant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTenantResponse {
    return { tenant: isSet(object.tenant) ? Tenant.fromJSON(object.tenant) : undefined };
  },

  toJSON(message: DeleteTenantResponse): unknown {
    const obj: any = {};
    if (message.tenant !== undefined) {
      obj.tenant = Tenant.toJSON(message.tenant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTenantResponse>, I>>(base?: I): DeleteTenantResponse {
    return DeleteTenantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTenantResponse>, I>>(object: I): DeleteTenantResponse {
    const message = createBaseDeleteTenantResponse();
    message.tenant = (object.tenant !== undefined && object.tenant !== null)
      ? Tenant.fromPartial(object.tenant)
      : undefined;
    return message;
  },
};

function createBaseReadTenantRequest(): ReadTenantRequest {
  return { filter: "" };
}

export const ReadTenantRequest: MessageFns<ReadTenantRequest> = {
  encode(message: ReadTenantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== "") {
      writer.uint32(10).string(message.filter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadTenantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadTenantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadTenantRequest {
    return { filter: isSet(object.filter) ? globalThis.String(object.filter) : "" };
  },

  toJSON(message: ReadTenantRequest): unknown {
    const obj: any = {};
    if (message.filter !== "") {
      obj.filter = message.filter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadTenantRequest>, I>>(base?: I): ReadTenantRequest {
    return ReadTenantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadTenantRequest>, I>>(object: I): ReadTenantRequest {
    const message = createBaseReadTenantRequest();
    message.filter = object.filter ?? "";
    return message;
  },
};

function createBaseReadTenantResponse(): ReadTenantResponse {
  return { tenant: undefined };
}

export const ReadTenantResponse: MessageFns<ReadTenantResponse> = {
  encode(message: ReadTenantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenant !== undefined) {
      Tenant.encode(message.tenant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadTenantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadTenantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenant = Tenant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadTenantResponse {
    return { tenant: isSet(object.tenant) ? Tenant.fromJSON(object.tenant) : undefined };
  },

  toJSON(message: ReadTenantResponse): unknown {
    const obj: any = {};
    if (message.tenant !== undefined) {
      obj.tenant = Tenant.toJSON(message.tenant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadTenantResponse>, I>>(base?: I): ReadTenantResponse {
    return ReadTenantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadTenantResponse>, I>>(object: I): ReadTenantResponse {
    const message = createBaseReadTenantResponse();
    message.tenant = (object.tenant !== undefined && object.tenant !== null)
      ? Tenant.fromPartial(object.tenant)
      : undefined;
    return message;
  },
};

function createBaseUpdateTenantRequest(): UpdateTenantRequest {
  return { id: "", data: undefined };
}

export const UpdateTenantRequest: MessageFns<UpdateTenantRequest> = {
  encode(message: UpdateTenantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.data !== undefined) {
      UpdateTenantPayload.encode(message.data, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTenantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTenantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = UpdateTenantPayload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTenantRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      data: isSet(object.data) ? UpdateTenantPayload.fromJSON(object.data) : undefined,
    };
  },

  toJSON(message: UpdateTenantRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.data !== undefined) {
      obj.data = UpdateTenantPayload.toJSON(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTenantRequest>, I>>(base?: I): UpdateTenantRequest {
    return UpdateTenantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTenantRequest>, I>>(object: I): UpdateTenantRequest {
    const message = createBaseUpdateTenantRequest();
    message.id = object.id ?? "";
    message.data = (object.data !== undefined && object.data !== null)
      ? UpdateTenantPayload.fromPartial(object.data)
      : undefined;
    return message;
  },
};

function createBaseUpdateTenantResponse(): UpdateTenantResponse {
  return { tenant: undefined };
}

export const UpdateTenantResponse: MessageFns<UpdateTenantResponse> = {
  encode(message: UpdateTenantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tenant !== undefined) {
      Tenant.encode(message.tenant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTenantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTenantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tenant = Tenant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTenantResponse {
    return { tenant: isSet(object.tenant) ? Tenant.fromJSON(object.tenant) : undefined };
  },

  toJSON(message: UpdateTenantResponse): unknown {
    const obj: any = {};
    if (message.tenant !== undefined) {
      obj.tenant = Tenant.toJSON(message.tenant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTenantResponse>, I>>(base?: I): UpdateTenantResponse {
    return UpdateTenantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTenantResponse>, I>>(object: I): UpdateTenantResponse {
    const message = createBaseUpdateTenantResponse();
    message.tenant = (object.tenant !== undefined && object.tenant !== null)
      ? Tenant.fromPartial(object.tenant)
      : undefined;
    return message;
  },
};

function createBaseInviteMemberRequest(): InviteMemberRequest {
  return { email: "", userId: "", role: "" };
}

export const InviteMemberRequest: MessageFns<InviteMemberRequest> = {
  encode(message: InviteMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.role !== "") {
      writer.uint32(50).string(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InviteMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.role = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteMemberRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
    };
  },

  toJSON(message: InviteMemberRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteMemberRequest>, I>>(base?: I): InviteMemberRequest {
    return InviteMemberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteMemberRequest>, I>>(object: I): InviteMemberRequest {
    const message = createBaseInviteMemberRequest();
    message.email = object.email ?? "";
    message.userId = object.userId ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseInviteMemberResponse(): InviteMemberResponse {
  return { member: undefined };
}

export const InviteMemberResponse: MessageFns<InviteMemberResponse> = {
  encode(message: InviteMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.member !== undefined) {
      Member.encode(message.member, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InviteMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.member = Member.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteMemberResponse {
    return { member: isSet(object.member) ? Member.fromJSON(object.member) : undefined };
  },

  toJSON(message: InviteMemberResponse): unknown {
    const obj: any = {};
    if (message.member !== undefined) {
      obj.member = Member.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteMemberResponse>, I>>(base?: I): InviteMemberResponse {
    return InviteMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteMemberResponse>, I>>(object: I): InviteMemberResponse {
    const message = createBaseInviteMemberResponse();
    message.member = (object.member !== undefined && object.member !== null)
      ? Member.fromPartial(object.member)
      : undefined;
    return message;
  },
};

function createBaseFindMemberRequest(): FindMemberRequest {
  return { status: "", role: "", tenantId: "" };
}

export const FindMemberRequest: MessageFns<FindMemberRequest> = {
  encode(message: FindMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.role !== "") {
      writer.uint32(18).string(message.role);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindMemberRequest {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
    };
  },

  toJSON(message: FindMemberRequest): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindMemberRequest>, I>>(base?: I): FindMemberRequest {
    return FindMemberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindMemberRequest>, I>>(object: I): FindMemberRequest {
    const message = createBaseFindMemberRequest();
    message.status = object.status ?? "";
    message.role = object.role ?? "";
    message.tenantId = object.tenantId ?? "";
    return message;
  },
};

function createBaseFindMemberResponse(): FindMemberResponse {
  return { members: [] };
}

export const FindMemberResponse: MessageFns<FindMemberResponse> = {
  encode(message: FindMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.members) {
      Member.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FindMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.members.push(Member.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindMemberResponse {
    return {
      members: globalThis.Array.isArray(object?.members) ? object.members.map((e: any) => Member.fromJSON(e)) : [],
    };
  },

  toJSON(message: FindMemberResponse): unknown {
    const obj: any = {};
    if (message.members?.length) {
      obj.members = message.members.map((e) => Member.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindMemberResponse>, I>>(base?: I): FindMemberResponse {
    return FindMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindMemberResponse>, I>>(object: I): FindMemberResponse {
    const message = createBaseFindMemberResponse();
    message.members = object.members?.map((e) => Member.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeleteMemberRequest(): DeleteMemberRequest {
  return { id: "" };
}

export const DeleteMemberRequest: MessageFns<DeleteMemberRequest> = {
  encode(message: DeleteMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteMemberRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteMemberRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMemberRequest>, I>>(base?: I): DeleteMemberRequest {
    return DeleteMemberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMemberRequest>, I>>(object: I): DeleteMemberRequest {
    const message = createBaseDeleteMemberRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeleteMemberResponse(): DeleteMemberResponse {
  return { member: undefined };
}

export const DeleteMemberResponse: MessageFns<DeleteMemberResponse> = {
  encode(message: DeleteMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.member !== undefined) {
      Member.encode(message.member, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.member = Member.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteMemberResponse {
    return { member: isSet(object.member) ? Member.fromJSON(object.member) : undefined };
  },

  toJSON(message: DeleteMemberResponse): unknown {
    const obj: any = {};
    if (message.member !== undefined) {
      obj.member = Member.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMemberResponse>, I>>(base?: I): DeleteMemberResponse {
    return DeleteMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMemberResponse>, I>>(object: I): DeleteMemberResponse {
    const message = createBaseDeleteMemberResponse();
    message.member = (object.member !== undefined && object.member !== null)
      ? Member.fromPartial(object.member)
      : undefined;
    return message;
  },
};

function createBaseReadMemberRequest(): ReadMemberRequest {
  return { id: "" };
}

export const ReadMemberRequest: MessageFns<ReadMemberRequest> = {
  encode(message: ReadMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadMemberRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: ReadMemberRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadMemberRequest>, I>>(base?: I): ReadMemberRequest {
    return ReadMemberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadMemberRequest>, I>>(object: I): ReadMemberRequest {
    const message = createBaseReadMemberRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseReadMemberResponse(): ReadMemberResponse {
  return { member: undefined };
}

export const ReadMemberResponse: MessageFns<ReadMemberResponse> = {
  encode(message: ReadMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.member !== undefined) {
      Member.encode(message.member, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.member = Member.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadMemberResponse {
    return { member: isSet(object.member) ? Member.fromJSON(object.member) : undefined };
  },

  toJSON(message: ReadMemberResponse): unknown {
    const obj: any = {};
    if (message.member !== undefined) {
      obj.member = Member.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadMemberResponse>, I>>(base?: I): ReadMemberResponse {
    return ReadMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadMemberResponse>, I>>(object: I): ReadMemberResponse {
    const message = createBaseReadMemberResponse();
    message.member = (object.member !== undefined && object.member !== null)
      ? Member.fromPartial(object.member)
      : undefined;
    return message;
  },
};

function createBaseUpdateMemberRequest(): UpdateMemberRequest {
  return { id: "", status: "", role: "" };
}

export const UpdateMemberRequest: MessageFns<UpdateMemberRequest> = {
  encode(message: UpdateMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMemberRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
    };
  },

  toJSON(message: UpdateMemberRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMemberRequest>, I>>(base?: I): UpdateMemberRequest {
    return UpdateMemberRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMemberRequest>, I>>(object: I): UpdateMemberRequest {
    const message = createBaseUpdateMemberRequest();
    message.id = object.id ?? "";
    message.status = object.status ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseUpdateMemberResponse(): UpdateMemberResponse {
  return { member: undefined };
}

export const UpdateMemberResponse: MessageFns<UpdateMemberResponse> = {
  encode(message: UpdateMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.member !== undefined) {
      Member.encode(message.member, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.member = Member.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMemberResponse {
    return { member: isSet(object.member) ? Member.fromJSON(object.member) : undefined };
  },

  toJSON(message: UpdateMemberResponse): unknown {
    const obj: any = {};
    if (message.member !== undefined) {
      obj.member = Member.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMemberResponse>, I>>(base?: I): UpdateMemberResponse {
    return UpdateMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMemberResponse>, I>>(object: I): UpdateMemberResponse {
    const message = createBaseUpdateMemberResponse();
    message.member = (object.member !== undefined && object.member !== null)
      ? Member.fromPartial(object.member)
      : undefined;
    return message;
  },
};

function createBaseAcceptMemberInvitationRequest(): AcceptMemberInvitationRequest {
  return { token: "" };
}

export const AcceptMemberInvitationRequest: MessageFns<AcceptMemberInvitationRequest> = {
  encode(message: AcceptMemberInvitationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcceptMemberInvitationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcceptMemberInvitationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcceptMemberInvitationRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: AcceptMemberInvitationRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcceptMemberInvitationRequest>, I>>(base?: I): AcceptMemberInvitationRequest {
    return AcceptMemberInvitationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcceptMemberInvitationRequest>, I>>(
    object: I,
  ): AcceptMemberInvitationRequest {
    const message = createBaseAcceptMemberInvitationRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseAcceptMemberInvitationResponse(): AcceptMemberInvitationResponse {
  return { member: undefined };
}

export const AcceptMemberInvitationResponse: MessageFns<AcceptMemberInvitationResponse> = {
  encode(message: AcceptMemberInvitationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.member !== undefined) {
      Member.encode(message.member, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcceptMemberInvitationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcceptMemberInvitationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.member = Member.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AcceptMemberInvitationResponse {
    return { member: isSet(object.member) ? Member.fromJSON(object.member) : undefined };
  },

  toJSON(message: AcceptMemberInvitationResponse): unknown {
    const obj: any = {};
    if (message.member !== undefined) {
      obj.member = Member.toJSON(message.member);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AcceptMemberInvitationResponse>, I>>(base?: I): AcceptMemberInvitationResponse {
    return AcceptMemberInvitationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AcceptMemberInvitationResponse>, I>>(
    object: I,
  ): AcceptMemberInvitationResponse {
    const message = createBaseAcceptMemberInvitationResponse();
    message.member = (object.member !== undefined && object.member !== null)
      ? Member.fromPartial(object.member)
      : undefined;
    return message;
  },
};

export interface TenantService {
  /** Tenants */
  CreateTenant(request: CreateTenantRequest): Promise<CreateTenantResponse>;
  ReadTenant(request: ReadTenantRequest): Promise<ReadTenantResponse>;
  FindTenant(request: FindTenantRequest): Promise<FindTenantResponse>;
  UpdateTenant(request: UpdateTenantRequest): Promise<UpdateTenantResponse>;
  DeleteTenant(request: DeleteTenantRequest): Promise<DeleteTenantResponse>;
  TenantAvailable(request: TenantAvailableRequest): Promise<TenantAvailableResponse>;
  /** Members */
  InviteMember(request: InviteMemberRequest): Promise<InviteMemberResponse>;
  AcceptMemberInvitation(request: AcceptMemberInvitationRequest): Promise<AcceptMemberInvitationResponse>;
  UpdateMember(request: UpdateMemberRequest): Promise<UpdateMemberResponse>;
  DeleteMember(request: DeleteMemberRequest): Promise<DeleteMemberResponse>;
  ReadMember(request: ReadMemberRequest): Promise<ReadMemberResponse>;
  FindMembers(request: FindMemberRequest): Promise<FindMemberResponse>;
}

export const TenantServiceServiceName = "io.ultimatebackend.srv.tenant.TenantService";
export class TenantServiceClientImpl implements TenantService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TenantServiceServiceName;
    this.rpc = rpc;
    this.CreateTenant = this.CreateTenant.bind(this);
    this.ReadTenant = this.ReadTenant.bind(this);
    this.FindTenant = this.FindTenant.bind(this);
    this.UpdateTenant = this.UpdateTenant.bind(this);
    this.DeleteTenant = this.DeleteTenant.bind(this);
    this.TenantAvailable = this.TenantAvailable.bind(this);
    this.InviteMember = this.InviteMember.bind(this);
    this.AcceptMemberInvitation = this.AcceptMemberInvitation.bind(this);
    this.UpdateMember = this.UpdateMember.bind(this);
    this.DeleteMember = this.DeleteMember.bind(this);
    this.ReadMember = this.ReadMember.bind(this);
    this.FindMembers = this.FindMembers.bind(this);
  }
  CreateTenant(request: CreateTenantRequest): Promise<CreateTenantResponse> {
    const data = CreateTenantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateTenant", data);
    return promise.then((data) => CreateTenantResponse.decode(new BinaryReader(data)));
  }

  ReadTenant(request: ReadTenantRequest): Promise<ReadTenantResponse> {
    const data = ReadTenantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ReadTenant", data);
    return promise.then((data) => ReadTenantResponse.decode(new BinaryReader(data)));
  }

  FindTenant(request: FindTenantRequest): Promise<FindTenantResponse> {
    const data = FindTenantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindTenant", data);
    return promise.then((data) => FindTenantResponse.decode(new BinaryReader(data)));
  }

  UpdateTenant(request: UpdateTenantRequest): Promise<UpdateTenantResponse> {
    const data = UpdateTenantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateTenant", data);
    return promise.then((data) => UpdateTenantResponse.decode(new BinaryReader(data)));
  }

  DeleteTenant(request: DeleteTenantRequest): Promise<DeleteTenantResponse> {
    const data = DeleteTenantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteTenant", data);
    return promise.then((data) => DeleteTenantResponse.decode(new BinaryReader(data)));
  }

  TenantAvailable(request: TenantAvailableRequest): Promise<TenantAvailableResponse> {
    const data = TenantAvailableRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TenantAvailable", data);
    return promise.then((data) => TenantAvailableResponse.decode(new BinaryReader(data)));
  }

  InviteMember(request: InviteMemberRequest): Promise<InviteMemberResponse> {
    const data = InviteMemberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "InviteMember", data);
    return promise.then((data) => InviteMemberResponse.decode(new BinaryReader(data)));
  }

  AcceptMemberInvitation(request: AcceptMemberInvitationRequest): Promise<AcceptMemberInvitationResponse> {
    const data = AcceptMemberInvitationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AcceptMemberInvitation", data);
    return promise.then((data) => AcceptMemberInvitationResponse.decode(new BinaryReader(data)));
  }

  UpdateMember(request: UpdateMemberRequest): Promise<UpdateMemberResponse> {
    const data = UpdateMemberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateMember", data);
    return promise.then((data) => UpdateMemberResponse.decode(new BinaryReader(data)));
  }

  DeleteMember(request: DeleteMemberRequest): Promise<DeleteMemberResponse> {
    const data = DeleteMemberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteMember", data);
    return promise.then((data) => DeleteMemberResponse.decode(new BinaryReader(data)));
  }

  ReadMember(request: ReadMemberRequest): Promise<ReadMemberResponse> {
    const data = ReadMemberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ReadMember", data);
    return promise.then((data) => ReadMemberResponse.decode(new BinaryReader(data)));
  }

  FindMembers(request: FindMemberRequest): Promise<FindMemberResponse> {
    const data = FindMemberRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FindMembers", data);
    return promise.then((data) => FindMemberResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
