// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v7.35.1
// source: libs/proto-schema/src/proto/webhook.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'io.ultimatebackend.srv.webhook';

export enum WebhookRequestType {
  POST = 0,
  GET = 1,
  PUT = 2,
  DELETE = 3,
  PATCH = 4,
  UNRECOGNIZED = -1,
}

export function webhookRequestTypeFromJSON(object: any): WebhookRequestType {
  switch (object) {
    case 0:
    case 'POST':
      return WebhookRequestType.POST;
    case 1:
    case 'GET':
      return WebhookRequestType.GET;
    case 2:
    case 'PUT':
      return WebhookRequestType.PUT;
    case 3:
    case 'DELETE':
      return WebhookRequestType.DELETE;
    case 4:
    case 'PATCH':
      return WebhookRequestType.PATCH;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return WebhookRequestType.UNRECOGNIZED;
  }
}

export function webhookRequestTypeToJSON(object: WebhookRequestType): string {
  switch (object) {
    case WebhookRequestType.POST:
      return 'POST';
    case WebhookRequestType.GET:
      return 'GET';
    case WebhookRequestType.PUT:
      return 'PUT';
    case WebhookRequestType.DELETE:
      return 'DELETE';
    case WebhookRequestType.PATCH:
      return 'PATCH';
    case WebhookRequestType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export enum WebhookAuthType {
  NONE = 0,
  BASIC = 1,
  API_KEY = 2,
  TOKEN = 3,
  OAUTH_2 = 4,
  UNRECOGNIZED = -1,
}

export function webhookAuthTypeFromJSON(object: any): WebhookAuthType {
  switch (object) {
    case 0:
    case 'NONE':
      return WebhookAuthType.NONE;
    case 1:
    case 'BASIC':
      return WebhookAuthType.BASIC;
    case 2:
    case 'API_KEY':
      return WebhookAuthType.API_KEY;
    case 3:
    case 'TOKEN':
      return WebhookAuthType.TOKEN;
    case 4:
    case 'OAUTH_2':
      return WebhookAuthType.OAUTH_2;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return WebhookAuthType.UNRECOGNIZED;
  }
}

export function webhookAuthTypeToJSON(object: WebhookAuthType): string {
  switch (object) {
    case WebhookAuthType.NONE:
      return 'NONE';
    case WebhookAuthType.BASIC:
      return 'BASIC';
    case WebhookAuthType.API_KEY:
      return 'API_KEY';
    case WebhookAuthType.TOKEN:
      return 'TOKEN';
    case WebhookAuthType.OAUTH_2:
      return 'OAUTH_2';
    case WebhookAuthType.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export enum ApiKeyField {
  HEADER = 0,
  PARAMS = 1,
  UNRECOGNIZED = -1,
}

export function apiKeyFieldFromJSON(object: any): ApiKeyField {
  switch (object) {
    case 0:
    case 'HEADER':
      return ApiKeyField.HEADER;
    case 1:
    case 'PARAMS':
      return ApiKeyField.PARAMS;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return ApiKeyField.UNRECOGNIZED;
  }
}

export function apiKeyFieldToJSON(object: ApiKeyField): string {
  switch (object) {
    case ApiKeyField.HEADER:
      return 'HEADER';
    case ApiKeyField.PARAMS:
      return 'PARAMS';
    case ApiKeyField.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}

export interface Auth {
  type: string;
  identifier: string;
  addTo: string;
  key: string;
  value: string;
  token: string;
  username: string;
  password: string;
}

export interface Paginate {
  skip: number;
  limit: number;
}

export interface Webhook {
  id: string;
  endpoint: string;
  requestType: string;
  createdAt: string;
  updatedAt: string;
  tenantId: string;
  auth: Auth | undefined;
  active: boolean;
  name: string;
  action: string;
}

export interface CreateWebhookRequest {
  name: string;
  endpoint: string;
  requestType: string;
  auth: Auth | undefined;
}

export interface CreateWebhookResponse {
  webhook: Webhook | undefined;
}

export interface UpdateWebhookRequest {
  id: string;
  name: string;
  endpoint: string;
  requestType: string;
  auth: Auth | undefined;
}

export interface UpdateWebhookResponse {
  webhook: Webhook | undefined;
}

export interface DeleteWebhookRequest {
  id: string;
}

export interface DeleteWebhookResponse {
  webhook: Webhook | undefined;
}

export interface ReadWebhookRequest {
  id: string;
}

export interface ReadWebhookResponse {
  webhook: Webhook | undefined;
}

export interface FindWebhookRequest {
  filter: string;
  paginate: Paginate | undefined;
}

export interface FindWebhookResponse {
  webhooks: Webhook[];
}

function createBaseAuth(): Auth {
  return {
    type: '',
    identifier: '',
    addTo: '',
    key: '',
    value: '',
    token: '',
    username: '',
    password: '',
  };
}

export const Auth: MessageFns<Auth> = {
  encode(
    message: Auth,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.type !== '') {
      writer.uint32(10).string(message.type);
    }
    if (message.identifier !== '') {
      writer.uint32(18).string(message.identifier);
    }
    if (message.addTo !== '') {
      writer.uint32(26).string(message.addTo);
    }
    if (message.key !== '') {
      writer.uint32(34).string(message.key);
    }
    if (message.value !== '') {
      writer.uint32(42).string(message.value);
    }
    if (message.token !== '') {
      writer.uint32(50).string(message.token);
    }
    if (message.username !== '') {
      writer.uint32(58).string(message.username);
    }
    if (message.password !== '') {
      writer.uint32(66).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Auth {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.addTo = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Auth {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : '',
      identifier: isSet(object.identifier)
        ? globalThis.String(object.identifier)
        : '',
      addTo: isSet(object.addTo) ? globalThis.String(object.addTo) : '',
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
      token: isSet(object.token) ? globalThis.String(object.token) : '',
      username: isSet(object.username)
        ? globalThis.String(object.username)
        : '',
      password: isSet(object.password)
        ? globalThis.String(object.password)
        : '',
    };
  },

  toJSON(message: Auth): unknown {
    const obj: any = {};
    if (message.type !== '') {
      obj.type = message.type;
    }
    if (message.identifier !== '') {
      obj.identifier = message.identifier;
    }
    if (message.addTo !== '') {
      obj.addTo = message.addTo;
    }
    if (message.key !== '') {
      obj.key = message.key;
    }
    if (message.value !== '') {
      obj.value = message.value;
    }
    if (message.token !== '') {
      obj.token = message.token;
    }
    if (message.username !== '') {
      obj.username = message.username;
    }
    if (message.password !== '') {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Auth>, I>>(base?: I): Auth {
    return Auth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Auth>, I>>(object: I): Auth {
    const message = createBaseAuth();
    message.type = object.type ?? '';
    message.identifier = object.identifier ?? '';
    message.addTo = object.addTo ?? '';
    message.key = object.key ?? '';
    message.value = object.value ?? '';
    message.token = object.token ?? '';
    message.username = object.username ?? '';
    message.password = object.password ?? '';
    return message;
  },
};

function createBasePaginate(): Paginate {
  return { skip: 0, limit: 0 };
}

export const Paginate: MessageFns<Paginate> = {
  encode(
    message: Paginate,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.skip !== 0) {
      writer.uint32(8).int32(message.skip);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Paginate {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.skip = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Paginate {
    return {
      skip: isSet(object.skip) ? globalThis.Number(object.skip) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: Paginate): unknown {
    const obj: any = {};
    if (message.skip !== 0) {
      obj.skip = Math.round(message.skip);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Paginate>, I>>(base?: I): Paginate {
    return Paginate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Paginate>, I>>(object: I): Paginate {
    const message = createBasePaginate();
    message.skip = object.skip ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseWebhook(): Webhook {
  return {
    id: '',
    endpoint: '',
    requestType: '',
    createdAt: '',
    updatedAt: '',
    tenantId: '',
    auth: undefined,
    active: false,
    name: '',
    action: '',
  };
}

export const Webhook: MessageFns<Webhook> = {
  encode(
    message: Webhook,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.endpoint !== '') {
      writer.uint32(18).string(message.endpoint);
    }
    if (message.requestType !== '') {
      writer.uint32(26).string(message.requestType);
    }
    if (message.createdAt !== '') {
      writer.uint32(50).string(message.createdAt);
    }
    if (message.updatedAt !== '') {
      writer.uint32(58).string(message.updatedAt);
    }
    if (message.tenantId !== '') {
      writer.uint32(66).string(message.tenantId);
    }
    if (message.auth !== undefined) {
      Auth.encode(message.auth, writer.uint32(74).fork()).join();
    }
    if (message.active !== false) {
      writer.uint32(80).bool(message.active);
    }
    if (message.name !== '') {
      writer.uint32(90).string(message.name);
    }
    if (message.action !== '') {
      writer.uint32(98).string(message.action);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Webhook {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebhook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.auth = Auth.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.action = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Webhook {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      endpoint: isSet(object.endpoint)
        ? globalThis.String(object.endpoint)
        : '',
      requestType: isSet(object.requestType)
        ? globalThis.String(object.requestType)
        : '',
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : '',
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : '',
      auth: isSet(object.auth) ? Auth.fromJSON(object.auth) : undefined,
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      action: isSet(object.action) ? globalThis.String(object.action) : '',
    };
  },

  toJSON(message: Webhook): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.endpoint !== '') {
      obj.endpoint = message.endpoint;
    }
    if (message.requestType !== '') {
      obj.requestType = message.requestType;
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== '') {
      obj.updatedAt = message.updatedAt;
    }
    if (message.tenantId !== '') {
      obj.tenantId = message.tenantId;
    }
    if (message.auth !== undefined) {
      obj.auth = Auth.toJSON(message.auth);
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.action !== '') {
      obj.action = message.action;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Webhook>, I>>(base?: I): Webhook {
    return Webhook.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Webhook>, I>>(object: I): Webhook {
    const message = createBaseWebhook();
    message.id = object.id ?? '';
    message.endpoint = object.endpoint ?? '';
    message.requestType = object.requestType ?? '';
    message.createdAt = object.createdAt ?? '';
    message.updatedAt = object.updatedAt ?? '';
    message.tenantId = object.tenantId ?? '';
    message.auth =
      object.auth !== undefined && object.auth !== null
        ? Auth.fromPartial(object.auth)
        : undefined;
    message.active = object.active ?? false;
    message.name = object.name ?? '';
    message.action = object.action ?? '';
    return message;
  },
};

function createBaseCreateWebhookRequest(): CreateWebhookRequest {
  return { name: '', endpoint: '', requestType: '', auth: undefined };
}

export const CreateWebhookRequest: MessageFns<CreateWebhookRequest> = {
  encode(
    message: CreateWebhookRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.endpoint !== '') {
      writer.uint32(18).string(message.endpoint);
    }
    if (message.requestType !== '') {
      writer.uint32(26).string(message.requestType);
    }
    if (message.auth !== undefined) {
      Auth.encode(message.auth, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateWebhookRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.auth = Auth.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWebhookRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      endpoint: isSet(object.endpoint)
        ? globalThis.String(object.endpoint)
        : '',
      requestType: isSet(object.requestType)
        ? globalThis.String(object.requestType)
        : '',
      auth: isSet(object.auth) ? Auth.fromJSON(object.auth) : undefined,
    };
  },

  toJSON(message: CreateWebhookRequest): unknown {
    const obj: any = {};
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.endpoint !== '') {
      obj.endpoint = message.endpoint;
    }
    if (message.requestType !== '') {
      obj.requestType = message.requestType;
    }
    if (message.auth !== undefined) {
      obj.auth = Auth.toJSON(message.auth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWebhookRequest>, I>>(
    base?: I,
  ): CreateWebhookRequest {
    return CreateWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWebhookRequest>, I>>(
    object: I,
  ): CreateWebhookRequest {
    const message = createBaseCreateWebhookRequest();
    message.name = object.name ?? '';
    message.endpoint = object.endpoint ?? '';
    message.requestType = object.requestType ?? '';
    message.auth =
      object.auth !== undefined && object.auth !== null
        ? Auth.fromPartial(object.auth)
        : undefined;
    return message;
  },
};

function createBaseCreateWebhookResponse(): CreateWebhookResponse {
  return { webhook: undefined };
}

export const CreateWebhookResponse: MessageFns<CreateWebhookResponse> = {
  encode(
    message: CreateWebhookResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.webhook !== undefined) {
      Webhook.encode(message.webhook, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateWebhookResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhook = Webhook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateWebhookResponse {
    return {
      webhook: isSet(object.webhook)
        ? Webhook.fromJSON(object.webhook)
        : undefined,
    };
  },

  toJSON(message: CreateWebhookResponse): unknown {
    const obj: any = {};
    if (message.webhook !== undefined) {
      obj.webhook = Webhook.toJSON(message.webhook);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateWebhookResponse>, I>>(
    base?: I,
  ): CreateWebhookResponse {
    return CreateWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateWebhookResponse>, I>>(
    object: I,
  ): CreateWebhookResponse {
    const message = createBaseCreateWebhookResponse();
    message.webhook =
      object.webhook !== undefined && object.webhook !== null
        ? Webhook.fromPartial(object.webhook)
        : undefined;
    return message;
  },
};

function createBaseUpdateWebhookRequest(): UpdateWebhookRequest {
  return { id: '', name: '', endpoint: '', requestType: '', auth: undefined };
}

export const UpdateWebhookRequest: MessageFns<UpdateWebhookRequest> = {
  encode(
    message: UpdateWebhookRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(42).string(message.id);
    }
    if (message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.endpoint !== '') {
      writer.uint32(18).string(message.endpoint);
    }
    if (message.requestType !== '') {
      writer.uint32(26).string(message.requestType);
    }
    if (message.auth !== undefined) {
      Auth.encode(message.auth, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdateWebhookRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.auth = Auth.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWebhookRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      endpoint: isSet(object.endpoint)
        ? globalThis.String(object.endpoint)
        : '',
      requestType: isSet(object.requestType)
        ? globalThis.String(object.requestType)
        : '',
      auth: isSet(object.auth) ? Auth.fromJSON(object.auth) : undefined,
    };
  },

  toJSON(message: UpdateWebhookRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.name !== '') {
      obj.name = message.name;
    }
    if (message.endpoint !== '') {
      obj.endpoint = message.endpoint;
    }
    if (message.requestType !== '') {
      obj.requestType = message.requestType;
    }
    if (message.auth !== undefined) {
      obj.auth = Auth.toJSON(message.auth);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWebhookRequest>, I>>(
    base?: I,
  ): UpdateWebhookRequest {
    return UpdateWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWebhookRequest>, I>>(
    object: I,
  ): UpdateWebhookRequest {
    const message = createBaseUpdateWebhookRequest();
    message.id = object.id ?? '';
    message.name = object.name ?? '';
    message.endpoint = object.endpoint ?? '';
    message.requestType = object.requestType ?? '';
    message.auth =
      object.auth !== undefined && object.auth !== null
        ? Auth.fromPartial(object.auth)
        : undefined;
    return message;
  },
};

function createBaseUpdateWebhookResponse(): UpdateWebhookResponse {
  return { webhook: undefined };
}

export const UpdateWebhookResponse: MessageFns<UpdateWebhookResponse> = {
  encode(
    message: UpdateWebhookResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.webhook !== undefined) {
      Webhook.encode(message.webhook, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): UpdateWebhookResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhook = Webhook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWebhookResponse {
    return {
      webhook: isSet(object.webhook)
        ? Webhook.fromJSON(object.webhook)
        : undefined,
    };
  },

  toJSON(message: UpdateWebhookResponse): unknown {
    const obj: any = {};
    if (message.webhook !== undefined) {
      obj.webhook = Webhook.toJSON(message.webhook);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWebhookResponse>, I>>(
    base?: I,
  ): UpdateWebhookResponse {
    return UpdateWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWebhookResponse>, I>>(
    object: I,
  ): UpdateWebhookResponse {
    const message = createBaseUpdateWebhookResponse();
    message.webhook =
      object.webhook !== undefined && object.webhook !== null
        ? Webhook.fromPartial(object.webhook)
        : undefined;
    return message;
  },
};

function createBaseDeleteWebhookRequest(): DeleteWebhookRequest {
  return { id: '' };
}

export const DeleteWebhookRequest: MessageFns<DeleteWebhookRequest> = {
  encode(
    message: DeleteWebhookRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): DeleteWebhookRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteWebhookRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: DeleteWebhookRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteWebhookRequest>, I>>(
    base?: I,
  ): DeleteWebhookRequest {
    return DeleteWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteWebhookRequest>, I>>(
    object: I,
  ): DeleteWebhookRequest {
    const message = createBaseDeleteWebhookRequest();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseDeleteWebhookResponse(): DeleteWebhookResponse {
  return { webhook: undefined };
}

export const DeleteWebhookResponse: MessageFns<DeleteWebhookResponse> = {
  encode(
    message: DeleteWebhookResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.webhook !== undefined) {
      Webhook.encode(message.webhook, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): DeleteWebhookResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhook = Webhook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteWebhookResponse {
    return {
      webhook: isSet(object.webhook)
        ? Webhook.fromJSON(object.webhook)
        : undefined,
    };
  },

  toJSON(message: DeleteWebhookResponse): unknown {
    const obj: any = {};
    if (message.webhook !== undefined) {
      obj.webhook = Webhook.toJSON(message.webhook);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteWebhookResponse>, I>>(
    base?: I,
  ): DeleteWebhookResponse {
    return DeleteWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteWebhookResponse>, I>>(
    object: I,
  ): DeleteWebhookResponse {
    const message = createBaseDeleteWebhookResponse();
    message.webhook =
      object.webhook !== undefined && object.webhook !== null
        ? Webhook.fromPartial(object.webhook)
        : undefined;
    return message;
  },
};

function createBaseReadWebhookRequest(): ReadWebhookRequest {
  return { id: '' };
}

export const ReadWebhookRequest: MessageFns<ReadWebhookRequest> = {
  encode(
    message: ReadWebhookRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadWebhookRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadWebhookRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : '' };
  },

  toJSON(message: ReadWebhookRequest): unknown {
    const obj: any = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadWebhookRequest>, I>>(
    base?: I,
  ): ReadWebhookRequest {
    return ReadWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadWebhookRequest>, I>>(
    object: I,
  ): ReadWebhookRequest {
    const message = createBaseReadWebhookRequest();
    message.id = object.id ?? '';
    return message;
  },
};

function createBaseReadWebhookResponse(): ReadWebhookResponse {
  return { webhook: undefined };
}

export const ReadWebhookResponse: MessageFns<ReadWebhookResponse> = {
  encode(
    message: ReadWebhookResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.webhook !== undefined) {
      Webhook.encode(message.webhook, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ReadWebhookResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhook = Webhook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadWebhookResponse {
    return {
      webhook: isSet(object.webhook)
        ? Webhook.fromJSON(object.webhook)
        : undefined,
    };
  },

  toJSON(message: ReadWebhookResponse): unknown {
    const obj: any = {};
    if (message.webhook !== undefined) {
      obj.webhook = Webhook.toJSON(message.webhook);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadWebhookResponse>, I>>(
    base?: I,
  ): ReadWebhookResponse {
    return ReadWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadWebhookResponse>, I>>(
    object: I,
  ): ReadWebhookResponse {
    const message = createBaseReadWebhookResponse();
    message.webhook =
      object.webhook !== undefined && object.webhook !== null
        ? Webhook.fromPartial(object.webhook)
        : undefined;
    return message;
  },
};

function createBaseFindWebhookRequest(): FindWebhookRequest {
  return { filter: '', paginate: undefined };
}

export const FindWebhookRequest: MessageFns<FindWebhookRequest> = {
  encode(
    message: FindWebhookRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.filter !== '') {
      writer.uint32(10).string(message.filter);
    }
    if (message.paginate !== undefined) {
      Paginate.encode(message.paginate, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindWebhookRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paginate = Paginate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindWebhookRequest {
    return {
      filter: isSet(object.filter) ? globalThis.String(object.filter) : '',
      paginate: isSet(object.paginate)
        ? Paginate.fromJSON(object.paginate)
        : undefined,
    };
  },

  toJSON(message: FindWebhookRequest): unknown {
    const obj: any = {};
    if (message.filter !== '') {
      obj.filter = message.filter;
    }
    if (message.paginate !== undefined) {
      obj.paginate = Paginate.toJSON(message.paginate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindWebhookRequest>, I>>(
    base?: I,
  ): FindWebhookRequest {
    return FindWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindWebhookRequest>, I>>(
    object: I,
  ): FindWebhookRequest {
    const message = createBaseFindWebhookRequest();
    message.filter = object.filter ?? '';
    message.paginate =
      object.paginate !== undefined && object.paginate !== null
        ? Paginate.fromPartial(object.paginate)
        : undefined;
    return message;
  },
};

function createBaseFindWebhookResponse(): FindWebhookResponse {
  return { webhooks: [] };
}

export const FindWebhookResponse: MessageFns<FindWebhookResponse> = {
  encode(
    message: FindWebhookResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.webhooks) {
      Webhook.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindWebhookResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.webhooks.push(Webhook.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindWebhookResponse {
    return {
      webhooks: globalThis.Array.isArray(object?.webhooks)
        ? object.webhooks.map((e: any) => Webhook.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FindWebhookResponse): unknown {
    const obj: any = {};
    if (message.webhooks?.length) {
      obj.webhooks = message.webhooks.map((e) => Webhook.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindWebhookResponse>, I>>(
    base?: I,
  ): FindWebhookResponse {
    return FindWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindWebhookResponse>, I>>(
    object: I,
  ): FindWebhookResponse {
    const message = createBaseFindWebhookResponse();
    message.webhooks =
      object.webhooks?.map((e) => Webhook.fromPartial(e)) || [];
    return message;
  },
};

export interface WebhookService {
  CreateWebhook(request: CreateWebhookRequest): Promise<CreateWebhookResponse>;
  UpdateWebhook(request: UpdateWebhookRequest): Promise<UpdateWebhookResponse>;
  DeleteWebhook(request: DeleteWebhookRequest): Promise<DeleteWebhookResponse>;
  ReadWebhook(request: ReadWebhookRequest): Promise<ReadWebhookResponse>;
  FindWebhook(request: FindWebhookRequest): Promise<FindWebhookResponse>;
}

export const WebhookServiceServiceName =
  'io.ultimatebackend.srv.webhook.WebhookService';
export class WebhookServiceClientImpl implements WebhookService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || WebhookServiceServiceName;
    this.rpc = rpc;
    this.CreateWebhook = this.CreateWebhook.bind(this);
    this.UpdateWebhook = this.UpdateWebhook.bind(this);
    this.DeleteWebhook = this.DeleteWebhook.bind(this);
    this.ReadWebhook = this.ReadWebhook.bind(this);
    this.FindWebhook = this.FindWebhook.bind(this);
  }
  CreateWebhook(request: CreateWebhookRequest): Promise<CreateWebhookResponse> {
    const data = CreateWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'CreateWebhook', data);
    return promise.then((data) =>
      CreateWebhookResponse.decode(new BinaryReader(data)),
    );
  }

  UpdateWebhook(request: UpdateWebhookRequest): Promise<UpdateWebhookResponse> {
    const data = UpdateWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'UpdateWebhook', data);
    return promise.then((data) =>
      UpdateWebhookResponse.decode(new BinaryReader(data)),
    );
  }

  DeleteWebhook(request: DeleteWebhookRequest): Promise<DeleteWebhookResponse> {
    const data = DeleteWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'DeleteWebhook', data);
    return promise.then((data) =>
      DeleteWebhookResponse.decode(new BinaryReader(data)),
    );
  }

  ReadWebhook(request: ReadWebhookRequest): Promise<ReadWebhookResponse> {
    const data = ReadWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'ReadWebhook', data);
    return promise.then((data) =>
      ReadWebhookResponse.decode(new BinaryReader(data)),
    );
  }

  FindWebhook(request: FindWebhookRequest): Promise<FindWebhookResponse> {
    const data = FindWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'FindWebhook', data);
    return promise.then((data) =>
      FindWebhookResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
